In [2]:
# from google.colab import drive
# drive.mount('/content/drive')

### 0. Загрузка данных

In [3]:
!pip install mne
!wget https://raw.githubusercontent.com/adasegroup/NEUROML2020/seminar1/seminar1/train.csv
!wget https://raw.githubusercontent.com/adasegroup/NEUROML2020/seminar1/seminar1/test.csv

--2025-12-28 21:31:19--  https://raw.githubusercontent.com/adasegroup/NEUROML2020/seminar1/seminar1/train.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5381138 (5.1M) [text/plain]
Saving to: ‘train.csv.1’

train.csv.1         100%[===================>]   5.13M  --.-KB/s    in 0.08s   

2025-12-28 21:31:19 (61.7 MB/s) - ‘train.csv.1’ saved [5381138/5381138]

--2025-12-28 21:31:19--  https://raw.githubusercontent.com/adasegroup/NEUROML2020/seminar1/seminar1/test.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3567877 (3.4M

In [4]:
!pip install lightautoml

In [6]:
import pandas as pd
import numpy as np
import mne

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, f1_score

from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

from lightautoml.automl.presets.tabular_presets import TabularAutoML
from lightautoml.tasks import Task

from src.dataset import get_target, calc_features

delimiter = "\n" + "-"*10

In [8]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')
df_train.head()

time  condition  epoch         C3         Cz         C4        Fp1  \
0     0          1      0  -5.885714  -2.533107   9.866895   7.962973   
1     1          1      0  -7.999715 -16.916729 -11.924855  17.955477   
2     2          1      0  -6.727283 -15.979567 -11.114195  17.183478   
3     3          1      0   6.819390  -0.204905  10.090124  20.265222   
4     4          1      0  13.129486  -5.817193   5.040633  19.462210   

        Fp2         F7         F3  ...         F8         T7        T8  \
0  5.694433  23.638605  27.899784  ...  23.588723  12.178548  0.685809   
1  8.526994  56.635981  28.508435  ...   1.045533  14.656061 -4.119778   
2  4.497028  43.914130  10.079754  ... -14.741630  14.793562 -6.624813   
3  7.843006  36.250611  13.291199  ...  -7.135541  21.723418 -2.276825   
4  9.634234  42.311729  20.641012  ...   0.015602  19.703190  3.739076   

         P7         P3         Pz         P4         P8         O1        O2  
0 -4.887397 -10.646985 -14.735646  -8.729323  -0.562578 -17.055458 -3.616732  
1 -4.632381 -17.980657 -23.456960 -12.960684  -9.639784 -20.233549 -1.229811  
2 -3.402757 -10.269473 -18.736144  -3.579046  -0.045658 -14.089755  2.453398  
3  2.066859   4.325365  -2.803322   8.835114  13.878945  -5.772410  7.657873  
4  2.714350   3.251047  -3.631448   3.212956   4.635574  -5.045448  5.086024  

[5 rows x 22 columns]

In [9]:
non_eeg = ['time', 'condition', 'epoch', 'target']
channels = [ch for ch in df_train.columns if ch not in non_eeg]

In [13]:
X = get_target(df_train)
X = X.merge(calc_features(df_train, channels), on='epoch')
y = X['condition'].apply(lambda x: 0 if x == 1 else 1)

X = X.drop(['epoch', 'condition'], axis=1)
y = y.astype(int)
y.name = 'target'
X = X.reset_index(drop=True)
y = y.reset_index(drop=True)

## 3. Моделирование (максимум 3.5 балла)
[0.25] Обоснование стратегии разделения данных (train-test split)
Особое внимание уделить предотвращению утечки данных

[0.25] LAMA бейзлайн:
- Минимум 2 различные конфигурации
- Выбор лучшего решения

[3.0] Собственное решение (если не удалось побить LLama baseline: 3 x 1.0 балл за различные пайплайны/попытки):
- Выбор модели
- Построение пайплайна (препроцессинг, обработка пропусков, генерация признаков, отбор признаков, финальная модель/ансамбль)
- Оптимизация гиперпараметров

In [14]:
# Cтратегии разделения данных:
# В соответствием с выводами из файла EDA (part 1) делаем корректный train-test split по данным, предварительно подготовленным по эпохам
npr = np.random.RandomState(42)
epoch_list = X.index
train_idx, test_idx = train_test_split(epoch_list, test_size=0.33, random_state=42) ### делаем разбиение по эпохам как независимым объектам, чтобы избежать утечки между зависимыми наблюдениями, поскольку эпохи коррелированы внутри себя

X_train = X.iloc[train_idx]
X_test = X.iloc[test_idx]
y_train = y.iloc[train_idx]
y_test = y.iloc[test_idx]


In [15]:
# Подготовим данные для конфигураций
roles = {'target': 'target'}
task = Task('binary')

train_LAMA = X_train.copy()
train_LAMA['target'] = y_train.values

test_LAMA = X_test.copy()
test_LAMA['target'] = y_test.values

#### Конфигурация 1 - Классический LAMA (default)
Стандартная конфигурация - подбор лучших моделей (LGB, CatBoost и др.) с автотюнингом. Используем пресеты "по умолчанию".

In [16]:
automl1 = TabularAutoML(
    task=task,
    timeout=600,
    cpu_limit=2,
)
oof_pred1 = automl1.fit_predict(train_LAMA, roles=roles, verbose=2)
test_pred1 = automl1.predict(test_LAMA)

auc1 = roc_auc_score(y_test, test_pred1.data[:, 0])
f1_1 = f1_score(y_test, test_pred1.data[:, 0] > 0.5)
print(f"[LAMA Default] ROC-AUC: {auc1:.4f} F1: {f1_1:.4f}")

[21:33:26] Stdout logging level is INFO2.


INFO:lightautoml.automl.presets.base:Stdout logging level is INFO2.


[21:33:26] Copying TaskTimer may affect the parent PipelineTimer, so copy will create new unlimited TaskTimer


[21:33:26] Task: binary



INFO:lightautoml.automl.presets.base:Task: binary



[21:33:26] Start automl preset with listed constraints:


INFO:lightautoml.automl.presets.base:Start automl preset with listed constraints:


[21:33:26] - time: 600.00 seconds


INFO:lightautoml.automl.presets.base:- time: 600.00 seconds


[21:33:26] - CPU: 2 cores


INFO:lightautoml.automl.presets.base:- CPU: 2 cores


[21:33:26] - memory: 16 GB



INFO:lightautoml.automl.presets.base:- memory: 16 GB



[21:33:26] Train data shape: (120, 20)



INFO:lightautoml.reader.base:Train data shape: (120, 20)

INFO3:lightautoml.reader.base:Feats was rejected during automatic roles guess: []


[21:33:36] Layer 1 train process start. Time left 590.12 secs


INFO:lightautoml.automl.base:Layer 1 train process start. Time left 590.12 secs


[21:33:36] Start fitting Lvl_0_Pipe_0_Mod_0_LinearL2 ...


INFO:lightautoml.ml_algo.base:Start fitting Lvl_0_Pipe_0_Mod_0_LinearL2 ...
DEBUG:lightautoml.ml_algo.base:Training params: {'tol': 1e-06, 'max_iter': 100, 'cs': [1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50, 100, 500, 1000, 5000, 10000, 50000, 100000], 'early_stopping': 2, 'categorical_idx': [0, 1], 'embed_sizes': array([11, 11], dtype=int32), 'data_size': 27}


[21:33:36] ===== Start working with fold 0 for Lvl_0_Pipe_0_Mod_0_LinearL2 =====


INFO2:lightautoml.ml_algo.base:===== Start working with fold 0 for Lvl_0_Pipe_0_Mod_0_LinearL2 =====
INFO3:lightautoml.ml_algo.torch_based.linear_model:Linear model: C = 1e-05 score = 0.5555555555555556
INFO3:lightautoml.ml_algo.torch_based.linear_model:Linear model: C = 5e-05 score = 0.5625
INFO3:lightautoml.ml_algo.torch_based.linear_model:Linear model: C = 0.0001 score = 0.5625
INFO3:lightautoml.ml_algo.torch_based.linear_model:Linear model: C = 0.0005 score = 0.5694444444444444
INFO3:lightautoml.ml_algo.torch_based.linear_model:Linear model: C = 0.001 score = 0.5763888888888888
INFO3:lightautoml.ml_algo.torch_based.linear_model:Linear model: C = 0.005 score = 0.5694444444444444
INFO3:lightautoml.ml_algo.torch_based.linear_model:Linear model: C = 0.01 score = 0.5694444444444444


[21:33:36] ===== Start working with fold 1 for Lvl_0_Pipe_0_Mod_0_LinearL2 =====


INFO2:lightautoml.ml_algo.base:===== Start working with fold 1 for Lvl_0_Pipe_0_Mod_0_LinearL2 =====
INFO3:lightautoml.ml_algo.torch_based.linear_model:Linear model: C = 1e-05 score = 0.7062937062937064
INFO3:lightautoml.ml_algo.torch_based.linear_model:Linear model: C = 5e-05 score = 0.7062937062937064
INFO3:lightautoml.ml_algo.torch_based.linear_model:Linear model: C = 0.0001 score = 0.7062937062937064


[21:33:36] ===== Start working with fold 2 for Lvl_0_Pipe_0_Mod_0_LinearL2 =====


INFO2:lightautoml.ml_algo.base:===== Start working with fold 2 for Lvl_0_Pipe_0_Mod_0_LinearL2 =====
INFO3:lightautoml.ml_algo.torch_based.linear_model:Linear model: C = 1e-05 score = 0.8041958041958042
INFO3:lightautoml.ml_algo.torch_based.linear_model:Linear model: C = 5e-05 score = 0.8041958041958042
INFO3:lightautoml.ml_algo.torch_based.linear_model:Linear model: C = 0.0001 score = 0.8041958041958042


[21:33:36] ===== Start working with fold 3 for Lvl_0_Pipe_0_Mod_0_LinearL2 =====


INFO2:lightautoml.ml_algo.base:===== Start working with fold 3 for Lvl_0_Pipe_0_Mod_0_LinearL2 =====
INFO3:lightautoml.ml_algo.torch_based.linear_model:Linear model: C = 1e-05 score = 0.4755244755244755
INFO3:lightautoml.ml_algo.torch_based.linear_model:Linear model: C = 5e-05 score = 0.4755244755244755
INFO3:lightautoml.ml_algo.torch_based.linear_model:Linear model: C = 0.0001 score = 0.4755244755244755


[21:33:36] ===== Start working with fold 4 for Lvl_0_Pipe_0_Mod_0_LinearL2 =====


INFO2:lightautoml.ml_algo.base:===== Start working with fold 4 for Lvl_0_Pipe_0_Mod_0_LinearL2 =====
INFO3:lightautoml.ml_algo.torch_based.linear_model:Linear model: C = 1e-05 score = 0.951048951048951
INFO3:lightautoml.ml_algo.torch_based.linear_model:Linear model: C = 5e-05 score = 0.951048951048951
INFO3:lightautoml.ml_algo.torch_based.linear_model:Linear model: C = 0.0001 score = 0.951048951048951


[21:33:37] Fitting Lvl_0_Pipe_0_Mod_0_LinearL2 finished. score = 0.5680803571428572


INFO:lightautoml.ml_algo.base:Fitting Lvl_0_Pipe_0_Mod_0_LinearL2 finished. score = 0.5680803571428572


[21:33:37] Lvl_0_Pipe_0_Mod_0_LinearL2 fitting and predicting completed


INFO:lightautoml.ml_algo.base:Lvl_0_Pipe_0_Mod_0_LinearL2 fitting and predicting completed


[21:33:37] Time left 589.38 secs



INFO:lightautoml.automl.base:Time left 589.38 secs

INFO3:lightautoml.ml_algo.boost_lgbm:Training until validation scores don't improve for 200 rounds
INFO3:lightautoml.ml_algo.boost_lgbm:[100]	valid's auc: 0.520833
INFO3:lightautoml.ml_algo.boost_lgbm:[200]	valid's auc: 0.534722
INFO3:lightautoml.ml_algo.boost_lgbm:Early stopping, best iteration is:
[51]	valid's auc: 0.569444


[21:33:37] Selector_LightGBM fitting and predicting completed


INFO:lightautoml.ml_algo.base:Selector_LightGBM fitting and predicting completed


[21:33:37] Start fitting Lvl_0_Pipe_1_Mod_0_LightGBM ...


INFO:lightautoml.ml_algo.base:Start fitting Lvl_0_Pipe_1_Mod_0_LightGBM ...
DEBUG:lightautoml.ml_algo.base:Training params: {'task': 'train', 'learning_rate': 0.01, 'num_leaves': 16, 'feature_fraction': 0.7, 'bagging_fraction': 0.7, 'bagging_freq': 1, 'max_depth': -1, 'verbosity': -1, 'reg_alpha': 1, 'reg_lambda': 0.0, 'min_split_gain': 0.0, 'zero_as_missing': False, 'num_threads': 2, 'max_bin': 255, 'min_data_in_bin': 3, 'num_trees': 3000, 'early_stopping_rounds': 200, 'random_state': 42, 'verbose_eval': 100}


[21:33:37] ===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_0_LightGBM =====


INFO2:lightautoml.ml_algo.base:===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_0_LightGBM =====
INFO3:lightautoml.ml_algo.boost_lgbm:Training until validation scores don't improve for 200 rounds
INFO3:lightautoml.ml_algo.boost_lgbm:[100]	valid's auc: 0.5625
INFO3:lightautoml.ml_algo.boost_lgbm:[200]	valid's auc: 0.5625
INFO3:lightautoml.ml_algo.boost_lgbm:[300]	valid's auc: 0.548611
INFO3:lightautoml.ml_algo.boost_lgbm:Early stopping, best iteration is:
[198]	valid's auc: 0.576389


[21:33:37] ===== Start working with fold 1 for Lvl_0_Pipe_1_Mod_0_LightGBM =====


INFO2:lightautoml.ml_algo.base:===== Start working with fold 1 for Lvl_0_Pipe_1_Mod_0_LightGBM =====
INFO3:lightautoml.ml_algo.boost_lgbm:Training until validation scores don't improve for 200 rounds
INFO3:lightautoml.ml_algo.boost_lgbm:[100]	valid's auc: 0.727273
INFO3:lightautoml.ml_algo.boost_lgbm:[200]	valid's auc: 0.734266
INFO3:lightautoml.ml_algo.boost_lgbm:Early stopping, best iteration is:
[2]	valid's auc: 0.800699


[21:33:37] ===== Start working with fold 2 for Lvl_0_Pipe_1_Mod_0_LightGBM =====


INFO2:lightautoml.ml_algo.base:===== Start working with fold 2 for Lvl_0_Pipe_1_Mod_0_LightGBM =====
INFO3:lightautoml.ml_algo.boost_lgbm:Training until validation scores don't improve for 200 rounds
INFO3:lightautoml.ml_algo.boost_lgbm:[100]	valid's auc: 0.797203
INFO3:lightautoml.ml_algo.boost_lgbm:[200]	valid's auc: 0.811189
INFO3:lightautoml.ml_algo.boost_lgbm:Early stopping, best iteration is:
[89]	valid's auc: 0.825175


[21:33:37] ===== Start working with fold 3 for Lvl_0_Pipe_1_Mod_0_LightGBM =====


INFO2:lightautoml.ml_algo.base:===== Start working with fold 3 for Lvl_0_Pipe_1_Mod_0_LightGBM =====
INFO3:lightautoml.ml_algo.boost_lgbm:Training until validation scores don't improve for 200 rounds
INFO3:lightautoml.ml_algo.boost_lgbm:[100]	valid's auc: 0.611888
INFO3:lightautoml.ml_algo.boost_lgbm:[200]	valid's auc: 0.625874
INFO3:lightautoml.ml_algo.boost_lgbm:Early stopping, best iteration is:
[4]	valid's auc: 0.65035


[21:33:37] ===== Start working with fold 4 for Lvl_0_Pipe_1_Mod_0_LightGBM =====


INFO2:lightautoml.ml_algo.base:===== Start working with fold 4 for Lvl_0_Pipe_1_Mod_0_LightGBM =====
INFO3:lightautoml.ml_algo.boost_lgbm:Training until validation scores don't improve for 200 rounds
INFO3:lightautoml.ml_algo.boost_lgbm:[100]	valid's auc: 0.86014
INFO3:lightautoml.ml_algo.boost_lgbm:[200]	valid's auc: 0.818182
INFO3:lightautoml.ml_algo.boost_lgbm:[300]	valid's auc: 0.818182
INFO3:lightautoml.ml_algo.boost_lgbm:Early stopping, best iteration is:
[103]	valid's auc: 0.867133


[21:33:37] Fitting Lvl_0_Pipe_1_Mod_0_LightGBM finished. score = 0.6541573660714286


INFO:lightautoml.ml_algo.base:Fitting Lvl_0_Pipe_1_Mod_0_LightGBM finished. score = 0.6541573660714286


[21:33:37] Lvl_0_Pipe_1_Mod_0_LightGBM fitting and predicting completed


INFO:lightautoml.ml_algo.base:Lvl_0_Pipe_1_Mod_0_LightGBM fitting and predicting completed


[21:33:37] Start hyperparameters optimization for Lvl_0_Pipe_1_Mod_1_Tuned_LightGBM ... Time budget is 130.56 secs


INFO:lightautoml.ml_algo.tuning.optuna:Start hyperparameters optimization for Lvl_0_Pipe_1_Mod_1_Tuned_LightGBM ... Time budget is 130.56 secs
Optimization Progress:   0%|          | 0/101 [00:00<?, ?it/s]INFO:optuna.storages._in_memory:A new study created in memory with name: no-name-1d8ca92d-a646-41c1-8baf-a69249a76ad7
INFO3:lightautoml.ml_algo.boost_lgbm:Training until validation scores don't improve for 200 rounds
INFO3:lightautoml.ml_algo.boost_lgbm:[100]	valid's auc: 0.513889
INFO3:lightautoml.ml_algo.boost_lgbm:[200]	valid's auc: 0.5
INFO3:lightautoml.ml_algo.boost_lgbm:Early stopping, best iteration is:
[62]	valid's auc: 0.527778
INFO:optuna.study.study:Trial 0 finished with value: 0.5277777777777779 and parameters: {'feature_fraction': 0.6872700594236812, 'num_leaves': 244, 'bagging_fraction': 0.8659969709057025, 'min_sum_hessian_in_leaf': 0.24810409748678125, 'reg_alpha': 2.5361081166471375e-07, 'reg_lambda': 2.5348407664333426e-07}. Best is trial 0 with value: 0.527777777777

[21:33:50] Hyperparameters optimization for Lvl_0_Pipe_1_Mod_1_Tuned_LightGBM completed



INFO:lightautoml.ml_algo.tuning.optuna:Hyperparameters optimization for Lvl_0_Pipe_1_Mod_1_Tuned_LightGBM completed


[21:33:50] The set of hyperparameters {'feature_fraction': 0.9713386595732587, 'num_leaves': 28, 'bagging_fraction': 0.5263780042015709, 'min_sum_hessian_in_leaf': 0.0014715560349285325, 'reg_alpha': 0.005765667774595165, 'reg_lambda': 3.843066912688489e-07}
 achieve 0.6354 auc


INFO2:lightautoml.ml_algo.tuning.optuna:The set of hyperparameters {'feature_fraction': 0.9713386595732587, 'num_leaves': 28, 'bagging_fraction': 0.5263780042015709, 'min_sum_hessian_in_leaf': 0.0014715560349285325, 'reg_alpha': 0.005765667774595165, 'reg_lambda': 3.843066912688489e-07}
 achieve 0.6354 auc


[21:33:50] Start fitting Lvl_0_Pipe_1_Mod_1_Tuned_LightGBM ...


INFO:lightautoml.ml_algo.base:Start fitting Lvl_0_Pipe_1_Mod_1_Tuned_LightGBM ...
DEBUG:lightautoml.ml_algo.base:Training params: {'task': 'train', 'learning_rate': 0.05, 'num_leaves': 28, 'feature_fraction': 0.9713386595732587, 'bagging_fraction': 0.5263780042015709, 'bagging_freq': 1, 'max_depth': -1, 'verbosity': -1, 'reg_alpha': 0.005765667774595165, 'reg_lambda': 3.843066912688489e-07, 'min_split_gain': 0.0, 'zero_as_missing': False, 'num_threads': 2, 'max_bin': 255, 'min_data_in_bin': 3, 'num_trees': 3000, 'early_stopping_rounds': 100, 'random_state': 42, 'verbose_eval': 100, 'min_sum_hessian_in_leaf': 0.0014715560349285325}


[21:33:50] ===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_1_Tuned_LightGBM =====


INFO2:lightautoml.ml_algo.base:===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_1_Tuned_LightGBM =====
INFO3:lightautoml.ml_algo.boost_lgbm:Training until validation scores don't improve for 100 rounds
INFO3:lightautoml.ml_algo.boost_lgbm:[100]	valid's auc: 0.576389
INFO3:lightautoml.ml_algo.boost_lgbm:Early stopping, best iteration is:
[5]	valid's auc: 0.614583


[21:33:50] ===== Start working with fold 1 for Lvl_0_Pipe_1_Mod_1_Tuned_LightGBM =====


INFO2:lightautoml.ml_algo.base:===== Start working with fold 1 for Lvl_0_Pipe_1_Mod_1_Tuned_LightGBM =====
INFO3:lightautoml.ml_algo.boost_lgbm:Training until validation scores don't improve for 100 rounds
INFO3:lightautoml.ml_algo.boost_lgbm:[100]	valid's auc: 0.566434
INFO3:lightautoml.ml_algo.boost_lgbm:Early stopping, best iteration is:
[3]	valid's auc: 0.706294


[21:33:50] ===== Start working with fold 2 for Lvl_0_Pipe_1_Mod_1_Tuned_LightGBM =====


INFO2:lightautoml.ml_algo.base:===== Start working with fold 2 for Lvl_0_Pipe_1_Mod_1_Tuned_LightGBM =====
INFO3:lightautoml.ml_algo.boost_lgbm:Training until validation scores don't improve for 100 rounds
INFO3:lightautoml.ml_algo.boost_lgbm:[100]	valid's auc: 0.727273
INFO3:lightautoml.ml_algo.boost_lgbm:Early stopping, best iteration is:
[20]	valid's auc: 0.863636


[21:33:50] ===== Start working with fold 3 for Lvl_0_Pipe_1_Mod_1_Tuned_LightGBM =====


INFO2:lightautoml.ml_algo.base:===== Start working with fold 3 for Lvl_0_Pipe_1_Mod_1_Tuned_LightGBM =====
INFO3:lightautoml.ml_algo.boost_lgbm:Training until validation scores don't improve for 100 rounds
INFO3:lightautoml.ml_algo.boost_lgbm:[100]	valid's auc: 0.611888
INFO3:lightautoml.ml_algo.boost_lgbm:Early stopping, best iteration is:
[23]	valid's auc: 0.65035


[21:33:50] ===== Start working with fold 4 for Lvl_0_Pipe_1_Mod_1_Tuned_LightGBM =====


INFO2:lightautoml.ml_algo.base:===== Start working with fold 4 for Lvl_0_Pipe_1_Mod_1_Tuned_LightGBM =====
INFO3:lightautoml.ml_algo.boost_lgbm:Training until validation scores don't improve for 100 rounds
INFO3:lightautoml.ml_algo.boost_lgbm:[100]	valid's auc: 0.867133
INFO3:lightautoml.ml_algo.boost_lgbm:Early stopping, best iteration is:
[6]	valid's auc: 0.93007


[21:33:50] Fitting Lvl_0_Pipe_1_Mod_1_Tuned_LightGBM finished. score = 0.6961495535714286


INFO:lightautoml.ml_algo.base:Fitting Lvl_0_Pipe_1_Mod_1_Tuned_LightGBM finished. score = 0.6961495535714286


[21:33:50] Lvl_0_Pipe_1_Mod_1_Tuned_LightGBM fitting and predicting completed


INFO:lightautoml.ml_algo.base:Lvl_0_Pipe_1_Mod_1_Tuned_LightGBM fitting and predicting completed


[21:33:50] Start fitting Lvl_0_Pipe_1_Mod_2_CatBoost ...


INFO:lightautoml.ml_algo.base:Start fitting Lvl_0_Pipe_1_Mod_2_CatBoost ...
DEBUG:lightautoml.ml_algo.base:Training params: {'task_type': 'CPU', 'thread_count': 2, 'random_seed': 42, 'num_trees': 500, 'learning_rate': 0.02, 'l2_leaf_reg': 0.01, 'bootstrap_type': 'Bernoulli', 'grow_policy': 'SymmetricTree', 'max_depth': 5, 'min_data_in_leaf': 1, 'one_hot_max_size': 10, 'fold_permutation_block': 1, 'boosting_type': 'Plain', 'boost_from_average': True, 'od_type': 'Iter', 'od_wait': 100, 'max_bin': 32, 'feature_border_type': 'GreedyLogSum', 'nan_mode': 'Min', 'verbose': 100, 'allow_writing_files': False, 'verbose_eval': 100}


[21:33:50] ===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_2_CatBoost =====


INFO2:lightautoml.ml_algo.base:===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_2_CatBoost =====
INFO3:lightautoml.ml_algo.boost_cb:0:	test: 0.4409722	best: 0.4409722 (0)	total: 47.8ms	remaining: 23.9s
INFO3:lightautoml.ml_algo.boost_cb:100:	test: 0.5347222	best: 0.5347222 (84)	total: 118ms	remaining: 465ms
INFO3:lightautoml.ml_algo.boost_cb:Stopped by overfitting detector  (100 iterations wait)
INFO3:lightautoml.ml_algo.boost_cb:bestTest = 0.5347222222
INFO3:lightautoml.ml_algo.boost_cb:bestIteration = 84
INFO3:lightautoml.ml_algo.boost_cb:Shrink model to first 85 iterations.


[21:33:50] ===== Start working with fold 1 for Lvl_0_Pipe_1_Mod_2_CatBoost =====


INFO2:lightautoml.ml_algo.base:===== Start working with fold 1 for Lvl_0_Pipe_1_Mod_2_CatBoost =====
INFO3:lightautoml.ml_algo.boost_cb:0:	test: 0.5174825	best: 0.5174825 (0)	total: 1.03ms	remaining: 515ms
INFO3:lightautoml.ml_algo.boost_cb:100:	test: 0.6713287	best: 0.7062937 (49)	total: 69.1ms	remaining: 273ms
INFO3:lightautoml.ml_algo.boost_cb:Stopped by overfitting detector  (100 iterations wait)
INFO3:lightautoml.ml_algo.boost_cb:bestTest = 0.7062937063
INFO3:lightautoml.ml_algo.boost_cb:bestIteration = 49
INFO3:lightautoml.ml_algo.boost_cb:Shrink model to first 50 iterations.


[21:33:50] ===== Start working with fold 2 for Lvl_0_Pipe_1_Mod_2_CatBoost =====


INFO2:lightautoml.ml_algo.base:===== Start working with fold 2 for Lvl_0_Pipe_1_Mod_2_CatBoost =====
INFO3:lightautoml.ml_algo.boost_cb:0:	test: 0.7762238	best: 0.7762238 (0)	total: 4.04ms	remaining: 2.02s
INFO3:lightautoml.ml_algo.boost_cb:100:	test: 0.8111888	best: 0.8951049 (8)	total: 80.7ms	remaining: 319ms
INFO3:lightautoml.ml_algo.boost_cb:Stopped by overfitting detector  (100 iterations wait)
INFO3:lightautoml.ml_algo.boost_cb:bestTest = 0.8951048951
INFO3:lightautoml.ml_algo.boost_cb:bestIteration = 8
INFO3:lightautoml.ml_algo.boost_cb:Shrink model to first 9 iterations.


[21:33:51] ===== Start working with fold 3 for Lvl_0_Pipe_1_Mod_2_CatBoost =====


INFO2:lightautoml.ml_algo.base:===== Start working with fold 3 for Lvl_0_Pipe_1_Mod_2_CatBoost =====
INFO3:lightautoml.ml_algo.boost_cb:0:	test: 0.6503497	best: 0.6503497 (0)	total: 1.11ms	remaining: 556ms
INFO3:lightautoml.ml_algo.boost_cb:100:	test: 0.6083916	best: 0.6608392 (2)	total: 73.1ms	remaining: 289ms
INFO3:lightautoml.ml_algo.boost_cb:Stopped by overfitting detector  (100 iterations wait)
INFO3:lightautoml.ml_algo.boost_cb:bestTest = 0.6608391608
INFO3:lightautoml.ml_algo.boost_cb:bestIteration = 2
INFO3:lightautoml.ml_algo.boost_cb:Shrink model to first 3 iterations.


[21:33:51] ===== Start working with fold 4 for Lvl_0_Pipe_1_Mod_2_CatBoost =====


INFO2:lightautoml.ml_algo.base:===== Start working with fold 4 for Lvl_0_Pipe_1_Mod_2_CatBoost =====
INFO3:lightautoml.ml_algo.boost_cb:0:	test: 0.5944056	best: 0.5944056 (0)	total: 1.38ms	remaining: 688ms
INFO3:lightautoml.ml_algo.boost_cb:100:	test: 0.8881119	best: 0.8951049 (10)	total: 80.1ms	remaining: 316ms
INFO3:lightautoml.ml_algo.boost_cb:200:	test: 0.8321678	best: 0.9020979 (101)	total: 150ms	remaining: 223ms
INFO3:lightautoml.ml_algo.boost_cb:Stopped by overfitting detector  (100 iterations wait)
INFO3:lightautoml.ml_algo.boost_cb:bestTest = 0.9020979021
INFO3:lightautoml.ml_algo.boost_cb:bestIteration = 101
INFO3:lightautoml.ml_algo.boost_cb:Shrink model to first 102 iterations.


[21:33:51] Fitting Lvl_0_Pipe_1_Mod_2_CatBoost finished. score = 0.6544363839285715


INFO:lightautoml.ml_algo.base:Fitting Lvl_0_Pipe_1_Mod_2_CatBoost finished. score = 0.6544363839285715


[21:33:51] Lvl_0_Pipe_1_Mod_2_CatBoost fitting and predicting completed


INFO:lightautoml.ml_algo.base:Lvl_0_Pipe_1_Mod_2_CatBoost fitting and predicting completed


[21:33:51] Start hyperparameters optimization for Lvl_0_Pipe_1_Mod_3_Tuned_CatBoost ... Time budget is 300.00 secs


INFO:lightautoml.ml_algo.tuning.optuna:Start hyperparameters optimization for Lvl_0_Pipe_1_Mod_3_Tuned_CatBoost ... Time budget is 300.00 secs
Optimization Progress:   0%|          | 0/101 [00:00<?, ?it/s]INFO:optuna.storages._in_memory:A new study created in memory with name: no-name-b45bc9ac-edd0-492c-85be-cf136fe09d55
INFO3:lightautoml.ml_algo.boost_cb:0:	test: 0.4548611	best: 0.4548611 (0)	total: 1.35ms	remaining: 672ms
INFO3:lightautoml.ml_algo.boost_cb:100:	test: 0.5347222	best: 0.5486111 (64)	total: 72.9ms	remaining: 288ms
INFO3:lightautoml.ml_algo.boost_cb:Stopped by overfitting detector  (100 iterations wait)
INFO3:lightautoml.ml_algo.boost_cb:bestTest = 0.5486111111
INFO3:lightautoml.ml_algo.boost_cb:bestIteration = 64
INFO3:lightautoml.ml_algo.boost_cb:Shrink model to first 65 iterations.
INFO:optuna.study.study:Trial 0 finished with value: 0.5486111111111112 and parameters: {'max_depth': 4, 'l2_leaf_reg': 3.6010467344475403, 'min_data_in_leaf': 15}. Best is trial 0 with val

[21:34:16] Hyperparameters optimization for Lvl_0_Pipe_1_Mod_3_Tuned_CatBoost completed



INFO:lightautoml.ml_algo.tuning.optuna:Hyperparameters optimization for Lvl_0_Pipe_1_Mod_3_Tuned_CatBoost completed


[21:34:16] The set of hyperparameters {'max_depth': 4, 'l2_leaf_reg': 5.347108898782771e-06, 'min_data_in_leaf': 12}
 achieve 0.6250 auc


INFO2:lightautoml.ml_algo.tuning.optuna:The set of hyperparameters {'max_depth': 4, 'l2_leaf_reg': 5.347108898782771e-06, 'min_data_in_leaf': 12}
 achieve 0.6250 auc


[21:34:16] Start fitting Lvl_0_Pipe_1_Mod_3_Tuned_CatBoost ...


INFO:lightautoml.ml_algo.base:Start fitting Lvl_0_Pipe_1_Mod_3_Tuned_CatBoost ...
DEBUG:lightautoml.ml_algo.base:Training params: {'task_type': 'CPU', 'thread_count': 2, 'random_seed': 42, 'num_trees': 3000, 'learning_rate': 0.03, 'l2_leaf_reg': 5.347108898782771e-06, 'bootstrap_type': 'Bernoulli', 'grow_policy': 'SymmetricTree', 'max_depth': 4, 'min_data_in_leaf': 12, 'one_hot_max_size': 10, 'fold_permutation_block': 1, 'boosting_type': 'Plain', 'boost_from_average': True, 'od_type': 'Iter', 'od_wait': 100, 'max_bin': 32, 'feature_border_type': 'GreedyLogSum', 'nan_mode': 'Min', 'verbose': 100, 'allow_writing_files': False, 'verbose_eval': 100}


[21:34:16] ===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_3_Tuned_CatBoost =====


INFO2:lightautoml.ml_algo.base:===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_3_Tuned_CatBoost =====
INFO3:lightautoml.ml_algo.boost_cb:0:	test: 0.4479167	best: 0.4479167 (0)	total: 1.08ms	remaining: 3.24s
INFO3:lightautoml.ml_algo.boost_cb:100:	test: 0.5694444	best: 0.5972222 (77)	total: 82ms	remaining: 2.35s
INFO3:lightautoml.ml_algo.boost_cb:Stopped by overfitting detector  (100 iterations wait)
INFO3:lightautoml.ml_algo.boost_cb:bestTest = 0.5972222222
INFO3:lightautoml.ml_algo.boost_cb:bestIteration = 77
INFO3:lightautoml.ml_algo.boost_cb:Shrink model to first 78 iterations.


[21:34:16] ===== Start working with fold 1 for Lvl_0_Pipe_1_Mod_3_Tuned_CatBoost =====


INFO2:lightautoml.ml_algo.base:===== Start working with fold 1 for Lvl_0_Pipe_1_Mod_3_Tuned_CatBoost =====
INFO3:lightautoml.ml_algo.boost_cb:0:	test: 0.5104895	best: 0.5104895 (0)	total: 1.12ms	remaining: 3.36s
INFO3:lightautoml.ml_algo.boost_cb:100:	test: 0.7202797	best: 0.8741259 (33)	total: 84.5ms	remaining: 2.42s
INFO3:lightautoml.ml_algo.boost_cb:Stopped by overfitting detector  (100 iterations wait)
INFO3:lightautoml.ml_algo.boost_cb:bestTest = 0.8741258741
INFO3:lightautoml.ml_algo.boost_cb:bestIteration = 33
INFO3:lightautoml.ml_algo.boost_cb:Shrink model to first 34 iterations.


[21:34:16] ===== Start working with fold 2 for Lvl_0_Pipe_1_Mod_3_Tuned_CatBoost =====


INFO2:lightautoml.ml_algo.base:===== Start working with fold 2 for Lvl_0_Pipe_1_Mod_3_Tuned_CatBoost =====
INFO3:lightautoml.ml_algo.boost_cb:0:	test: 0.8006993	best: 0.8006993 (0)	total: 1.01ms	remaining: 3.04s
INFO3:lightautoml.ml_algo.boost_cb:100:	test: 0.7622378	best: 0.8321678 (5)	total: 66.8ms	remaining: 1.92s
INFO3:lightautoml.ml_algo.boost_cb:Stopped by overfitting detector  (100 iterations wait)
INFO3:lightautoml.ml_algo.boost_cb:bestTest = 0.8321678322
INFO3:lightautoml.ml_algo.boost_cb:bestIteration = 5
INFO3:lightautoml.ml_algo.boost_cb:Shrink model to first 6 iterations.


[21:34:17] ===== Start working with fold 3 for Lvl_0_Pipe_1_Mod_3_Tuned_CatBoost =====


INFO2:lightautoml.ml_algo.base:===== Start working with fold 3 for Lvl_0_Pipe_1_Mod_3_Tuned_CatBoost =====
INFO3:lightautoml.ml_algo.boost_cb:0:	test: 0.6503497	best: 0.6503497 (0)	total: 1.16ms	remaining: 3.49s
INFO3:lightautoml.ml_algo.boost_cb:100:	test: 0.6433566	best: 0.7202797 (3)	total: 64.2ms	remaining: 1.84s
INFO3:lightautoml.ml_algo.boost_cb:Stopped by overfitting detector  (100 iterations wait)
INFO3:lightautoml.ml_algo.boost_cb:bestTest = 0.7202797203
INFO3:lightautoml.ml_algo.boost_cb:bestIteration = 3
INFO3:lightautoml.ml_algo.boost_cb:Shrink model to first 4 iterations.


[21:34:17] ===== Start working with fold 4 for Lvl_0_Pipe_1_Mod_3_Tuned_CatBoost =====


INFO2:lightautoml.ml_algo.base:===== Start working with fold 4 for Lvl_0_Pipe_1_Mod_3_Tuned_CatBoost =====
INFO3:lightautoml.ml_algo.boost_cb:0:	test: 0.6013986	best: 0.6013986 (0)	total: 2.08ms	remaining: 6.23s
INFO3:lightautoml.ml_algo.boost_cb:100:	test: 0.8461538	best: 0.8741259 (73)	total: 68.8ms	remaining: 1.98s
INFO3:lightautoml.ml_algo.boost_cb:200:	test: 0.8461538	best: 0.8951049 (169)	total: 139ms	remaining: 1.94s
INFO3:lightautoml.ml_algo.boost_cb:Stopped by overfitting detector  (100 iterations wait)
INFO3:lightautoml.ml_algo.boost_cb:bestTest = 0.8951048951
INFO3:lightautoml.ml_algo.boost_cb:bestIteration = 169
INFO3:lightautoml.ml_algo.boost_cb:Shrink model to first 170 iterations.


[21:34:17] Fitting Lvl_0_Pipe_1_Mod_3_Tuned_CatBoost finished. score = 0.7366071428571428


INFO:lightautoml.ml_algo.base:Fitting Lvl_0_Pipe_1_Mod_3_Tuned_CatBoost finished. score = 0.7366071428571428


[21:34:17] Lvl_0_Pipe_1_Mod_3_Tuned_CatBoost fitting and predicting completed


INFO:lightautoml.ml_algo.base:Lvl_0_Pipe_1_Mod_3_Tuned_CatBoost fitting and predicting completed


[21:34:17] Time left 549.01 secs



INFO:lightautoml.automl.base:Time left 549.01 secs



[21:34:17] Layer 1 training completed.



INFO:lightautoml.automl.base:Layer 1 training completed.



[21:34:17] Blending: optimization starts with equal weights. Score = 0.7123326


INFO:lightautoml.automl.blend:Blending: optimization starts with equal weights. Score = 0.7123326


[21:34:17] Blending: iteration 0: score = 0.7385603, weights = [0.41398153 0.06656854 0.14960875 0.         0.3698412 ]


INFO:lightautoml.automl.blend:Blending: iteration 0: score = 0.7385603, weights = [0.41398153 0.06656854 0.14960875 0.         0.3698412 ]


[21:34:17] Blending: iteration 1: score = 0.7424665, weights = [0.46047238 0.         0.15539142 0.         0.38413626]


INFO:lightautoml.automl.blend:Blending: iteration 1: score = 0.7424665, weights = [0.46047238 0.         0.15539142 0.         0.38413626]


[21:34:17] Blending: iteration 2: score = 0.7430246, weights = [0.5419463  0.         0.09016994 0.         0.36788374]


INFO:lightautoml.automl.blend:Blending: iteration 2: score = 0.7430246, weights = [0.5419463  0.         0.09016994 0.         0.36788374]


[21:34:17] Blending: iteration 3: score = 0.7449777, weights = [0.6163315  0.         0.07662547 0.         0.30704305]


INFO:lightautoml.automl.blend:Blending: iteration 3: score = 0.7449777, weights = [0.6163315  0.         0.07662547 0.         0.30704305]


[21:34:17] Blending: no improvements for score. Terminated.



INFO:lightautoml.automl.blend:Blending: no improvements for score. Terminated.



[21:34:17] Blending: best score = 0.7449777, best weights = [0.6163315  0.         0.07662547 0.         0.30704305]


INFO:lightautoml.automl.blend:Blending: best score = 0.7449777, best weights = [0.6163315  0.         0.07662547 0.         0.30704305]


[21:34:17] Automl preset training completed in 51.40 seconds



INFO:lightautoml.automl.presets.base:Automl preset training completed in 51.40 seconds



[21:34:17] Model description:
Final prediction for new objects (level 0) = 
	 0.61633 * (5 averaged models Lvl_0_Pipe_0_Mod_0_LinearL2) +
	 0.07663 * (5 averaged models Lvl_0_Pipe_1_Mod_1_Tuned_LightGBM) +
	 0.30704 * (5 averaged models Lvl_0_Pipe_1_Mod_3_Tuned_CatBoost) 



INFO:lightautoml.automl.presets.base:Model description:
Final prediction for new objects (level 0) = 
	 0.61633 * (5 averaged models Lvl_0_Pipe_0_Mod_0_LinearL2) +
	 0.07663 * (5 averaged models Lvl_0_Pipe_1_Mod_1_Tuned_LightGBM) +
	 0.30704 * (5 averaged models Lvl_0_Pipe_1_Mod_3_Tuned_CatBoost) 



[LAMA Default] ROC-AUC: 0.7217 F1: 0.6557


### Конфигурация 2 — FAST, только lgbm
Используем только быстрый LightGBM.

In [17]:
automl2 = TabularAutoML(
    task=task,
    timeout=300,
    cpu_limit=2,
    general_params={
        'use_algos': [['lgb']]
    }
)
oof_pred2 = automl2.fit_predict(train_LAMA, roles=roles, verbose=1)
test_pred2 = automl2.predict(test_LAMA)

auc2 = roc_auc_score(y_test, test_pred2.data[:, 0])
f1_2 = f1_score(y_test, test_pred2.data[:, 0] > 0.5)
print(f'[LAMA FAST (lgb only)] ROC-AUC: {auc2:.4f}  F1: {f1_2:.4f}')


[21:34:18] Stdout logging level is INFO.


INFO:lightautoml.automl.presets.base:Stdout logging level is INFO.


[21:34:18] Task: binary



INFO:lightautoml.automl.presets.base:Task: binary



[21:34:18] Start automl preset with listed constraints:


INFO:lightautoml.automl.presets.base:Start automl preset with listed constraints:


[21:34:18] - time: 300.00 seconds


INFO:lightautoml.automl.presets.base:- time: 300.00 seconds


[21:34:18] - CPU: 2 cores


INFO:lightautoml.automl.presets.base:- CPU: 2 cores


[21:34:18] - memory: 16 GB



INFO:lightautoml.automl.presets.base:- memory: 16 GB



[21:34:18] Train data shape: (120, 20)



INFO:lightautoml.reader.base:Train data shape: (120, 20)

INFO3:lightautoml.reader.base:Feats was rejected during automatic roles guess: []


[21:34:18] Layer 1 train process start. Time left 299.86 secs


INFO:lightautoml.automl.base:Layer 1 train process start. Time left 299.86 secs
INFO3:lightautoml.ml_algo.boost_lgbm:Training until validation scores don't improve for 200 rounds
INFO3:lightautoml.ml_algo.boost_lgbm:[100]	valid's auc: 0.520833
INFO3:lightautoml.ml_algo.boost_lgbm:[200]	valid's auc: 0.534722
INFO3:lightautoml.ml_algo.boost_lgbm:Early stopping, best iteration is:
[51]	valid's auc: 0.569444


[21:34:18] Selector_LightGBM fitting and predicting completed


INFO:lightautoml.ml_algo.base:Selector_LightGBM fitting and predicting completed


[21:34:18] Start fitting Lvl_0_Pipe_0_Mod_0_LightGBM ...


INFO:lightautoml.ml_algo.base:Start fitting Lvl_0_Pipe_0_Mod_0_LightGBM ...
DEBUG:lightautoml.ml_algo.base:Training params: {'task': 'train', 'learning_rate': 0.01, 'num_leaves': 16, 'feature_fraction': 0.7, 'bagging_fraction': 0.7, 'bagging_freq': 1, 'max_depth': -1, 'verbosity': -1, 'reg_alpha': 1, 'reg_lambda': 0.0, 'min_split_gain': 0.0, 'zero_as_missing': False, 'num_threads': 2, 'max_bin': 255, 'min_data_in_bin': 3, 'num_trees': 3000, 'early_stopping_rounds': 200, 'random_state': 42, 'verbose_eval': 100}
INFO2:lightautoml.ml_algo.base:===== Start working with fold 0 for Lvl_0_Pipe_0_Mod_0_LightGBM =====
INFO3:lightautoml.ml_algo.boost_lgbm:Training until validation scores don't improve for 200 rounds
INFO3:lightautoml.ml_algo.boost_lgbm:[100]	valid's auc: 0.5625
INFO3:lightautoml.ml_algo.boost_lgbm:[200]	valid's auc: 0.5625
INFO3:lightautoml.ml_algo.boost_lgbm:[300]	valid's auc: 0.548611
INFO3:lightautoml.ml_algo.boost_lgbm:Early stopping, best iteration is:
[198]	valid's auc: 0.

[21:34:18] Fitting Lvl_0_Pipe_0_Mod_0_LightGBM finished. score = 0.6541573660714286


INFO:lightautoml.ml_algo.base:Fitting Lvl_0_Pipe_0_Mod_0_LightGBM finished. score = 0.6541573660714286


[21:34:18] Lvl_0_Pipe_0_Mod_0_LightGBM fitting and predicting completed


INFO:lightautoml.ml_algo.base:Lvl_0_Pipe_0_Mod_0_LightGBM fitting and predicting completed


[21:34:18] Time left 299.53 secs



INFO:lightautoml.automl.base:Time left 299.53 secs



[21:34:18] Layer 1 training completed.



INFO:lightautoml.automl.base:Layer 1 training completed.



[21:34:18] Automl preset training completed in 0.48 seconds



INFO:lightautoml.automl.presets.base:Automl preset training completed in 0.48 seconds



[21:34:18] Model description:
Final prediction for new objects (level 0) = 
	 1.00000 * (5 averaged models Lvl_0_Pipe_0_Mod_0_LightGBM) 



INFO:lightautoml.automl.presets.base:Model description:
Final prediction for new objects (level 0) = 
	 1.00000 * (5 averaged models Lvl_0_Pipe_0_Mod_0_LightGBM) 



[LAMA FAST (lgb only)] ROC-AUC: 0.7138  F1: 0.6552


### Конфигурация 3 - расширенный набор моделей и мощный автотюнинг

Включаем сразу несколько ансамблей (XGB, LGBM с тюнингом, CatBoost с тюнингом, MLP нейросеть) + используем продвинутую кросс-валидацию, автотюнинг с разными алгоритмами

In [18]:
automl3 = TabularAutoML(
    task=task,
    timeout=600,
    cpu_limit=2,
    general_params={
        'use_algos': [['xgb', 'lgb_tuned', 'cb_tuned'], ['mlp']],  # Много моделей
    },
    reader_params={
        'n_jobs': 2,
        'cv': 5,
        'random_state': 84,
        'advanced_roles': True,
    },
    tuning_params={'max_tuning_iter': "auto", 'max_tuning_time': 300},
    selection_params={'mode': 1}
)

oof_pred3 = automl3.fit_predict(train_LAMA, roles=roles, verbose=1)
test_pred3 = automl3.predict(test_LAMA)

auc3 = roc_auc_score(y_test, test_pred3.data[:, 0])
f1_3 = f1_score(y_test, test_pred3.data[:, 0] > 0.5)
print(f'[LAMA Advanced] ROC-AUC: {auc3:.4f}  F1: {f1_3:.4f}')


[21:34:18] Stdout logging level is INFO.


INFO:lightautoml.automl.presets.base:Stdout logging level is INFO.


[21:34:18] Task: binary



INFO:lightautoml.automl.presets.base:Task: binary



[21:34:18] Start automl preset with listed constraints:


INFO:lightautoml.automl.presets.base:Start automl preset with listed constraints:


[21:34:18] - time: 600.00 seconds


INFO:lightautoml.automl.presets.base:- time: 600.00 seconds


[21:34:18] - CPU: 2 cores


INFO:lightautoml.automl.presets.base:- CPU: 2 cores


[21:34:18] - memory: 16 GB



INFO:lightautoml.automl.presets.base:- memory: 16 GB



[21:34:18] Train data shape: (120, 20)



INFO:lightautoml.reader.base:Train data shape: (120, 20)

INFO3:lightautoml.reader.base:Feats was rejected during automatic roles guess: []


[21:34:18] Layer 1 train process start. Time left 599.86 secs


INFO:lightautoml.automl.base:Layer 1 train process start. Time left 599.86 secs
INFO3:lightautoml.ml_algo.boost_lgbm:Training until validation scores don't improve for 200 rounds
INFO3:lightautoml.ml_algo.boost_lgbm:[100]	valid's auc: 0.784722
INFO3:lightautoml.ml_algo.boost_lgbm:[200]	valid's auc: 0.743056
INFO3:lightautoml.ml_algo.boost_lgbm:[300]	valid's auc: 0.743056
INFO3:lightautoml.ml_algo.boost_lgbm:Early stopping, best iteration is:
[100]	valid's auc: 0.784722


[21:34:18] Selector_LightGBM fitting and predicting completed


INFO:lightautoml.ml_algo.base:Selector_LightGBM fitting and predicting completed


[21:34:18] Start hyperparameters optimization for Lvl_0_Pipe_0_Mod_0_Tuned_LightGBM ... Time budget is 84.57 secs


INFO:lightautoml.ml_algo.tuning.optuna:Start hyperparameters optimization for Lvl_0_Pipe_0_Mod_0_Tuned_LightGBM ... Time budget is 84.57 secs
Optimization Progress:   0%|          | 0/100 [00:00<?, ?it/s]INFO:optuna.storages._in_memory:A new study created in memory with name: no-name-bce27972-6ff6-4cc3-9cee-b994a924aa19
INFO3:lightautoml.ml_algo.boost_lgbm:Training until validation scores don't improve for 200 rounds
INFO3:lightautoml.ml_algo.boost_lgbm:[100]	valid's auc: 0.770833
INFO3:lightautoml.ml_algo.boost_lgbm:[200]	valid's auc: 0.75
INFO3:lightautoml.ml_algo.boost_lgbm:Early stopping, best iteration is:
[64]	valid's auc: 0.791667
INFO:optuna.study.study:Trial 0 finished with value: 0.7916666666666666 and parameters: {'feature_fraction': 0.6872700594236812, 'num_leaves': 244, 'bagging_fraction': 0.8659969709057025, 'min_sum_hessian_in_leaf': 0.24810409748678125}. Best is trial 0 with value: 0.7916666666666666.
INFO3:lightautoml.ml_algo.tuning.optuna:Trial 1 with hyperparameters 

[21:34:30] Hyperparameters optimization for Lvl_0_Pipe_0_Mod_0_Tuned_LightGBM completed



INFO:lightautoml.ml_algo.tuning.optuna:Hyperparameters optimization for Lvl_0_Pipe_0_Mod_0_Tuned_LightGBM completed
INFO2:lightautoml.ml_algo.tuning.optuna:The set of hyperparameters {'feature_fraction': 0.5102734049121492, 'num_leaves': 129, 'bagging_fraction': 0.9847685553939329, 'min_sum_hessian_in_leaf': 0.689539874561655}
 achieve 0.8785 auc


[21:34:30] Start fitting Lvl_0_Pipe_0_Mod_0_Tuned_LightGBM ...


INFO:lightautoml.ml_algo.base:Start fitting Lvl_0_Pipe_0_Mod_0_Tuned_LightGBM ...
DEBUG:lightautoml.ml_algo.base:Training params: {'task': 'train', 'learning_rate': 0.05, 'num_leaves': 129, 'feature_fraction': 0.5102734049121492, 'bagging_fraction': 0.9847685553939329, 'bagging_freq': 1, 'max_depth': -1, 'verbosity': -1, 'reg_alpha': 1, 'reg_lambda': 0.0, 'min_split_gain': 0.0, 'zero_as_missing': False, 'num_threads': 2, 'max_bin': 255, 'min_data_in_bin': 3, 'num_trees': 3000, 'early_stopping_rounds': 100, 'random_state': 42, 'verbose_eval': 100, 'min_sum_hessian_in_leaf': 0.689539874561655}
INFO2:lightautoml.ml_algo.base:===== Start working with fold 0 for Lvl_0_Pipe_0_Mod_0_Tuned_LightGBM =====
INFO3:lightautoml.ml_algo.boost_lgbm:Training until validation scores don't improve for 100 rounds
INFO3:lightautoml.ml_algo.boost_lgbm:[100]	valid's auc: 0.770833
INFO3:lightautoml.ml_algo.boost_lgbm:Early stopping, best iteration is:
[37]	valid's auc: 0.850694
INFO2:lightautoml.ml_algo.base:

[21:34:30] Fitting Lvl_0_Pipe_0_Mod_0_Tuned_LightGBM finished. score = 0.7660435267857142


INFO:lightautoml.ml_algo.base:Fitting Lvl_0_Pipe_0_Mod_0_Tuned_LightGBM finished. score = 0.7660435267857142


[21:34:30] Lvl_0_Pipe_0_Mod_0_Tuned_LightGBM fitting and predicting completed


INFO:lightautoml.ml_algo.base:Lvl_0_Pipe_0_Mod_0_Tuned_LightGBM fitting and predicting completed


[21:34:30] Start hyperparameters optimization for Lvl_0_Pipe_0_Mod_1_Tuned_CatBoost ... Time budget is 138.56 secs


INFO:lightautoml.ml_algo.tuning.optuna:Start hyperparameters optimization for Lvl_0_Pipe_0_Mod_1_Tuned_CatBoost ... Time budget is 138.56 secs
Optimization Progress:   0%|          | 0/100 [00:00<?, ?it/s]INFO:optuna.storages._in_memory:A new study created in memory with name: no-name-04d6403f-f2f8-4e8a-ab2b-1d28f7b2adcd
INFO3:lightautoml.ml_algo.boost_cb:0:	test: 0.7534722	best: 0.7534722 (0)	total: 2.64ms	remaining: 1.32s
INFO3:lightautoml.ml_algo.boost_cb:100:	test: 0.8472222	best: 0.8819444 (12)	total: 67ms	remaining: 265ms
INFO3:lightautoml.ml_algo.boost_cb:Stopped by overfitting detector  (100 iterations wait)
INFO3:lightautoml.ml_algo.boost_cb:bestTest = 0.8819444444
INFO3:lightautoml.ml_algo.boost_cb:bestIteration = 12
INFO3:lightautoml.ml_algo.boost_cb:Shrink model to first 13 iterations.
INFO:optuna.study.study:Trial 0 finished with value: 0.8819444444444444 and parameters: {'max_depth': 4, 'l2_leaf_reg': 3.6010467344475403, 'min_data_in_leaf': 15}. Best is trial 0 with value

[21:34:48] Hyperparameters optimization for Lvl_0_Pipe_0_Mod_1_Tuned_CatBoost completed



INFO:lightautoml.ml_algo.tuning.optuna:Hyperparameters optimization for Lvl_0_Pipe_0_Mod_1_Tuned_CatBoost completed
INFO2:lightautoml.ml_algo.tuning.optuna:The set of hyperparameters {'max_depth': 3, 'l2_leaf_reg': 1.4142208298719828e-05, 'min_data_in_leaf': 13}
 achieve 0.9306 auc


[21:34:48] Start fitting Lvl_0_Pipe_0_Mod_1_Tuned_CatBoost ...


INFO:lightautoml.ml_algo.base:Start fitting Lvl_0_Pipe_0_Mod_1_Tuned_CatBoost ...
DEBUG:lightautoml.ml_algo.base:Training params: {'task_type': 'CPU', 'thread_count': 2, 'random_seed': 42, 'num_trees': 3000, 'learning_rate': 0.03, 'l2_leaf_reg': 1.4142208298719828e-05, 'bootstrap_type': 'Bernoulli', 'grow_policy': 'SymmetricTree', 'max_depth': 3, 'min_data_in_leaf': 13, 'one_hot_max_size': 10, 'fold_permutation_block': 1, 'boosting_type': 'Plain', 'boost_from_average': True, 'od_type': 'Iter', 'od_wait': 100, 'max_bin': 32, 'feature_border_type': 'GreedyLogSum', 'nan_mode': 'Min', 'verbose': 100, 'allow_writing_files': False, 'verbose_eval': 100}
INFO2:lightautoml.ml_algo.base:===== Start working with fold 0 for Lvl_0_Pipe_0_Mod_1_Tuned_CatBoost =====
INFO3:lightautoml.ml_algo.boost_cb:0:	test: 0.8506944	best: 0.8506944 (0)	total: 893us	remaining: 2.68s
INFO3:lightautoml.ml_algo.boost_cb:100:	test: 0.7569444	best: 0.8923611 (4)	total: 62.2ms	remaining: 1.78s
INFO3:lightautoml.ml_algo.b

[21:34:49] Fitting Lvl_0_Pipe_0_Mod_1_Tuned_CatBoost finished. score = 0.7657645089285713


INFO:lightautoml.ml_algo.base:Fitting Lvl_0_Pipe_0_Mod_1_Tuned_CatBoost finished. score = 0.7657645089285713


[21:34:49] Lvl_0_Pipe_0_Mod_1_Tuned_CatBoost fitting and predicting completed


INFO:lightautoml.ml_algo.base:Lvl_0_Pipe_0_Mod_1_Tuned_CatBoost fitting and predicting completed


[21:34:49] Start fitting Lvl_0_Pipe_0_Mod_2_XGBoost ...


INFO:lightautoml.ml_algo.base:Start fitting Lvl_0_Pipe_0_Mod_2_XGBoost ...
DEBUG:lightautoml.ml_algo.base:Training params: {'n_estimators': 3000, 'early_stopping_rounds': 100, 'seed': 42, 'verbose_eval': 100, 'nthread': 2}
INFO2:lightautoml.ml_algo.base:===== Start working with fold 0 for Lvl_0_Pipe_0_Mod_2_XGBoost =====
INFO3:lightautoml.ml_algo.boost_xgb:[0]	valid-auc:0.76042
INFO3:lightautoml.ml_algo.boost_xgb:[100]	valid-auc:0.77778
INFO3:lightautoml.ml_algo.boost_xgb:[104]	valid-auc:0.77778
INFO2:lightautoml.ml_algo.base:===== Start working with fold 1 for Lvl_0_Pipe_0_Mod_2_XGBoost =====
INFO3:lightautoml.ml_algo.boost_xgb:[0]	valid-auc:0.75524
INFO3:lightautoml.ml_algo.boost_xgb:[100]	valid-auc:0.82517
INFO3:lightautoml.ml_algo.boost_xgb:[112]	valid-auc:0.82517
INFO2:lightautoml.ml_algo.base:===== Start working with fold 2 for Lvl_0_Pipe_0_Mod_2_XGBoost =====
INFO3:lightautoml.ml_algo.boost_xgb:[0]	valid-auc:0.81469
INFO3:lightautoml.ml_algo.boost_xgb:[100]	valid-auc:0.68531
INF

[21:34:49] Fitting Lvl_0_Pipe_0_Mod_2_XGBoost finished. score = 0.7287946428571428


INFO:lightautoml.ml_algo.base:Fitting Lvl_0_Pipe_0_Mod_2_XGBoost finished. score = 0.7287946428571428


[21:34:49] Lvl_0_Pipe_0_Mod_2_XGBoost fitting and predicting completed


INFO:lightautoml.ml_algo.base:Lvl_0_Pipe_0_Mod_2_XGBoost fitting and predicting completed


[21:34:49] Time left 568.84 secs



INFO:lightautoml.automl.base:Time left 568.84 secs



[21:34:49] Layer 1 training completed.



INFO:lightautoml.automl.base:Layer 1 training completed.



[21:34:49] Layer 2 train process start. Time left 568.83 secs


INFO:lightautoml.automl.base:Layer 2 train process start. Time left 568.83 secs
DEBUG:lightautoml.ml_algo.dl_model:number of text features: 0 
DEBUG:lightautoml.ml_algo.dl_model:number of categorical features: 0 
DEBUG:lightautoml.ml_algo.dl_model:number of continuous features: 22 


[21:34:49] Start fitting Lvl_1_Pipe_0_Mod_0_TorchNN_mlp_0 ...


INFO:lightautoml.ml_algo.base:Start fitting Lvl_1_Pipe_0_Mod_0_TorchNN_mlp_0 ...
DEBUG:lightautoml.ml_algo.base:Training params: {'num_workers': 0, 'pin_memory': False, 'max_length': 256, 'is_snap': False, 'input_bn': False, 'max_emb_size': 256, 'bert_name': None, 'pooling': 'cls', 'device': device(type='cpu'), 'use_cont': True, 'use_cat': True, 'use_text': False, 'lang': 'en', 'deterministic': True, 'multigpu': False, 'random_state': 42, 'model': 'mlp', 'model_with_emb': False, 'path_to_save': None, 'verbose_inside': None, 'verbose': 1, 'n_epochs': 50, 'snap_params': {'k': 3, 'early_stopping': True, 'patience': 10, 'swa': True}, 'bs': 256, 'emb_dropout': 0.1, 'emb_ratio': 3, 'opt': 'Adam', 'opt_params': {'lr': 0.0003, 'weight_decay': 0}, 'sch': 'ReduceLROnPlateau', 'scheduler_params': {'patience': 5, 'factor': 0.5, 'min_lr': 1e-05}, 'loss': None, 'loss_params': {}, 'loss_on_logits': True, 'clip_grad': False, 'clip_grad_params': {}, 'init_bias': True, 'dataset': 'UniversalDataset', 'tu

[21:34:53] Fitting Lvl_1_Pipe_0_Mod_0_TorchNN_mlp_0 finished. score = 0.4866071428571428


INFO:lightautoml.ml_algo.base:Fitting Lvl_1_Pipe_0_Mod_0_TorchNN_mlp_0 finished. score = 0.4866071428571428


[21:34:53] Lvl_1_Pipe_0_Mod_0_TorchNN_mlp_0 fitting and predicting completed


INFO:lightautoml.ml_algo.base:Lvl_1_Pipe_0_Mod_0_TorchNN_mlp_0 fitting and predicting completed


[21:34:53] Time left 565.21 secs



INFO:lightautoml.automl.base:Time left 565.21 secs



[21:34:53] Layer 2 training completed.



INFO:lightautoml.automl.base:Layer 2 training completed.



[21:34:53] Automl preset training completed in 34.80 seconds



INFO:lightautoml.automl.presets.base:Automl preset training completed in 34.80 seconds



[21:34:53] Model description:
Models on level 0:
	 5 averaged models Lvl_0_Pipe_0_Mod_0_Tuned_LightGBM
	 5 averaged models Lvl_0_Pipe_0_Mod_1_Tuned_CatBoost
	 5 averaged models Lvl_0_Pipe_0_Mod_2_XGBoost

Final prediction for new objects (level 1) = 
	 1.00000 * (5 averaged models Lvl_1_Pipe_0_Mod_0_TorchNN_mlp_0) 



INFO:lightautoml.automl.presets.base:Model description:
Models on level 0:
	 5 averaged models Lvl_0_Pipe_0_Mod_0_Tuned_LightGBM
	 5 averaged models Lvl_0_Pipe_0_Mod_1_Tuned_CatBoost
	 5 averaged models Lvl_0_Pipe_0_Mod_2_XGBoost

Final prediction for new objects (level 1) = 
	 1.00000 * (5 averaged models Lvl_1_Pipe_0_Mod_0_TorchNN_mlp_0) 



[LAMA Advanced] ROC-AUC: 0.5000  F1: 0.0000


### Конфигурация 4 - с feature selection и ограниченным набором моделей
Только LGBM (c hyperparameter tuning) и линейная регрессия; включён feature selection (оставляем 80% лучших признаков); гиперпараметры подбираются на holdout-валидации.


In [19]:
automl4 = TabularAutoML(
    task=task,
    timeout=600,
    cpu_limit=2,
    general_params={
        'use_algos': [['lgb_tuned', 'linear_l2']]  # Только LGBM + Linear
    },
    selection_params={
        'select_algos': ['gbm', 'linear_l2'],
        'selection_feats_rate': 0.8,
        'max_features_cnt_in_result': None,
    },
    tuning_params={
        'fit_on_holdout': True,
        'max_tuning_iter': 50,
        'max_tuning_time': 200,
    }
)

oof_pred4 = automl4.fit_predict(train_LAMA, roles=roles, verbose=1)
test_pred4 = automl4.predict(test_LAMA)

auc4 = roc_auc_score(y_test, test_pred4.data[:, 0])
f1_4 = f1_score(y_test, test_pred4.data[:, 0] > 0.5)
print(f'[LAMA FS+LGBM/Linear] ROC-AUC: {auc4:.4f}  F1: {f1_4:.4f}')


[21:34:56] Stdout logging level is INFO.


INFO:lightautoml.automl.presets.base:Stdout logging level is INFO.


[21:34:56] Task: binary



INFO:lightautoml.automl.presets.base:Task: binary



[21:34:56] Start automl preset with listed constraints:


INFO:lightautoml.automl.presets.base:Start automl preset with listed constraints:


[21:34:56] - time: 600.00 seconds


INFO:lightautoml.automl.presets.base:- time: 600.00 seconds


[21:34:56] - CPU: 2 cores


INFO:lightautoml.automl.presets.base:- CPU: 2 cores


[21:34:56] - memory: 16 GB



INFO:lightautoml.automl.presets.base:- memory: 16 GB



[21:34:56] Train data shape: (120, 20)



INFO:lightautoml.reader.base:Train data shape: (120, 20)

INFO3:lightautoml.reader.base:Feats was rejected during automatic roles guess: []


[21:34:56] Layer 1 train process start. Time left 599.85 secs


INFO:lightautoml.automl.base:Layer 1 train process start. Time left 599.85 secs
INFO3:lightautoml.ml_algo.boost_lgbm:Training until validation scores don't improve for 200 rounds
INFO3:lightautoml.ml_algo.boost_lgbm:[100]	valid's auc: 0.520833
INFO3:lightautoml.ml_algo.boost_lgbm:[200]	valid's auc: 0.534722
INFO3:lightautoml.ml_algo.boost_lgbm:Early stopping, best iteration is:
[51]	valid's auc: 0.569444


[21:34:56] Selector_LightGBM fitting and predicting completed


INFO:lightautoml.ml_algo.base:Selector_LightGBM fitting and predicting completed


[21:34:56] Start fitting Lvl_0_Pipe_0_Mod_0_LinearL2 ...


INFO:lightautoml.ml_algo.base:Start fitting Lvl_0_Pipe_0_Mod_0_LinearL2 ...
DEBUG:lightautoml.ml_algo.base:Training params: {'tol': 1e-06, 'max_iter': 100, 'cs': [1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50, 100, 500, 1000, 5000, 10000, 50000, 100000], 'early_stopping': 2, 'categorical_idx': [0], 'embed_sizes': array([11], dtype=int32), 'data_size': 17}
INFO2:lightautoml.ml_algo.base:===== Start working with fold 0 for Lvl_0_Pipe_0_Mod_0_LinearL2 =====
INFO3:lightautoml.ml_algo.torch_based.linear_model:Linear model: C = 1e-05 score = 0.5555555555555556
INFO3:lightautoml.ml_algo.torch_based.linear_model:Linear model: C = 5e-05 score = 0.5625
INFO3:lightautoml.ml_algo.torch_based.linear_model:Linear model: C = 0.0001 score = 0.5555555555555556
INFO3:lightautoml.ml_algo.torch_based.linear_model:Linear model: C = 0.0005 score = 0.5555555555555556
INFO2:lightautoml.ml_algo.base:===== Start working with fold 1 for Lvl_0_Pipe_0_Mod_0_LinearL2 =====
INFO3:lig

[21:34:56] Fitting Lvl_0_Pipe_0_Mod_0_LinearL2 finished. score = 0.5680803571428571


INFO:lightautoml.ml_algo.base:Fitting Lvl_0_Pipe_0_Mod_0_LinearL2 finished. score = 0.5680803571428571


[21:34:56] Lvl_0_Pipe_0_Mod_0_LinearL2 fitting and predicting completed


INFO:lightautoml.ml_algo.base:Lvl_0_Pipe_0_Mod_0_LinearL2 fitting and predicting completed


[21:34:56] Time left 599.44 secs



INFO:lightautoml.automl.base:Time left 599.44 secs



[21:34:56] Start hyperparameters optimization for Lvl_0_Pipe_1_Mod_0_Tuned_LightGBM ... Time budget is 200.00 secs


INFO:lightautoml.ml_algo.tuning.optuna:Start hyperparameters optimization for Lvl_0_Pipe_1_Mod_0_Tuned_LightGBM ... Time budget is 200.00 secs
Optimization Progress:   0%|          | 0/50 [00:00<?, ?it/s]INFO:optuna.storages._in_memory:A new study created in memory with name: no-name-ccd85662-5bc5-4104-bf18-e657bd32bddd
INFO3:lightautoml.ml_algo.boost_lgbm:Training until validation scores don't improve for 200 rounds
INFO3:lightautoml.ml_algo.boost_lgbm:[100]	valid's auc: 0.520833
INFO3:lightautoml.ml_algo.boost_lgbm:[200]	valid's auc: 0.493056
INFO3:lightautoml.ml_algo.boost_lgbm:Early stopping, best iteration is:
[50]	valid's auc: 0.520833
INFO:optuna.study.study:Trial 0 finished with value: 0.5208333333333334 and parameters: {'feature_fraction': 0.6872700594236812, 'num_leaves': 244, 'bagging_fraction': 0.8659969709057025, 'min_sum_hessian_in_leaf': 0.24810409748678125}. Best is trial 0 with value: 0.5208333333333334.
INFO3:lightautoml.ml_algo.tuning.optuna:Trial 1 with hyperparamet

[21:35:01] Hyperparameters optimization for Lvl_0_Pipe_1_Mod_0_Tuned_LightGBM completed



INFO:lightautoml.ml_algo.tuning.optuna:Hyperparameters optimization for Lvl_0_Pipe_1_Mod_0_Tuned_LightGBM completed
INFO2:lightautoml.ml_algo.tuning.optuna:The set of hyperparameters {'feature_fraction': 0.8124527509966039, 'num_leaves': 144, 'bagging_fraction': 0.5086792017528844, 'min_sum_hessian_in_leaf': 0.17837062520581531}
 achieve 0.6146 auc


[21:35:01] Start fitting Lvl_0_Pipe_1_Mod_0_Tuned_LightGBM ...


INFO:lightautoml.ml_algo.base:Start fitting Lvl_0_Pipe_1_Mod_0_Tuned_LightGBM ...
DEBUG:lightautoml.ml_algo.base:Training params: {'task': 'train', 'learning_rate': 0.05, 'num_leaves': 144, 'feature_fraction': 0.8124527509966039, 'bagging_fraction': 0.5086792017528844, 'bagging_freq': 1, 'max_depth': -1, 'verbosity': -1, 'reg_alpha': 1, 'reg_lambda': 0.0, 'min_split_gain': 0.0, 'zero_as_missing': False, 'num_threads': 2, 'max_bin': 255, 'min_data_in_bin': 3, 'num_trees': 3000, 'early_stopping_rounds': 100, 'random_state': 42, 'verbose_eval': 100, 'min_sum_hessian_in_leaf': 0.17837062520581531}
INFO2:lightautoml.ml_algo.base:===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_0_Tuned_LightGBM =====
INFO3:lightautoml.ml_algo.boost_lgbm:Training until validation scores don't improve for 100 rounds
INFO3:lightautoml.ml_algo.boost_lgbm:[100]	valid's auc: 0.597222
INFO3:lightautoml.ml_algo.boost_lgbm:Early stopping, best iteration is:
[5]	valid's auc: 0.614583
INFO2:lightautoml.ml_algo.base

[21:35:01] Fitting Lvl_0_Pipe_1_Mod_0_Tuned_LightGBM finished. score = 0.6868024553571428


INFO:lightautoml.ml_algo.base:Fitting Lvl_0_Pipe_1_Mod_0_Tuned_LightGBM finished. score = 0.6868024553571428


[21:35:01] Lvl_0_Pipe_1_Mod_0_Tuned_LightGBM fitting and predicting completed


INFO:lightautoml.ml_algo.base:Lvl_0_Pipe_1_Mod_0_Tuned_LightGBM fitting and predicting completed


[21:35:01] Time left 594.55 secs



INFO:lightautoml.automl.base:Time left 594.55 secs



[21:35:01] Layer 1 training completed.



INFO:lightautoml.automl.base:Layer 1 training completed.



[21:35:01] Blending: optimization starts with equal weights. Score = 0.6939174


INFO:lightautoml.automl.blend:Blending: optimization starts with equal weights. Score = 0.6939174


[21:35:01] Blending: iteration 0: score = 0.7134487, weights = [0.6623374  0.33766258]


INFO:lightautoml.automl.blend:Blending: iteration 0: score = 0.7134487, weights = [0.6623374  0.33766258]


[21:35:01] Blending: no improvements for score. Terminated.



INFO:lightautoml.automl.blend:Blending: no improvements for score. Terminated.



[21:35:01] Blending: best score = 0.7134487, best weights = [0.6623374  0.33766258]


INFO:lightautoml.automl.blend:Blending: best score = 0.7134487, best weights = [0.6623374  0.33766258]


[21:35:01] Automl preset training completed in 5.54 seconds



INFO:lightautoml.automl.presets.base:Automl preset training completed in 5.54 seconds



[21:35:01] Model description:
Final prediction for new objects (level 0) = 
	 0.66234 * (5 averaged models Lvl_0_Pipe_0_Mod_0_LinearL2) +
	 0.33766 * (5 averaged models Lvl_0_Pipe_1_Mod_0_Tuned_LightGBM) 



INFO:lightautoml.automl.presets.base:Model description:
Final prediction for new objects (level 0) = 
	 0.66234 * (5 averaged models Lvl_0_Pipe_0_Mod_0_LinearL2) +
	 0.33766 * (5 averaged models Lvl_0_Pipe_1_Mod_0_Tuned_LightGBM) 



[LAMA FS+LGBM/Linear] ROC-AUC: 0.7217  F1: 0.4082


#### Выбор лучшего

In [20]:
results = {}
results['LAMA_DEFAULT'] = (auc1, f1_1)
results['LAMA_FAST'] = (auc2, f1_2)
results['LAMA_ADVANCED'] = (auc3, f1_3)
results['LAMA_FS'] = (auc4, f1_4)
for k, v in results.items():
    print(f'{k:15}| ROC-AUC: {v[0]:.4f} | F1: {v[1]:.4f}')

best_lama_name = max(results, key=lambda k: results[k][0])
print(f'--> Лучший бэйзлайн: {best_lama_name}, ROC-AUC = {results[best_lama_name][0]:.4f}')

LAMA_DEFAULT   | ROC-AUC: 0.7217 | F1: 0.6557
LAMA_FAST      | ROC-AUC: 0.7138 | F1: 0.6552
LAMA_ADVANCED  | ROC-AUC: 0.5000 | F1: 0.0000
LAMA_FS        | ROC-AUC: 0.7217 | F1: 0.4082
--> Лучший бэйзлайн: LAMA_DEFAULT, ROC-AUC = 0.7217


Классическая конфигурация LAMA, несмотря на консерватизм, дала лучший результат среди тестируемых.

### Собственное решение 1

In [21]:
# PIPELINE 1: LightGBM + scale + auto feature selection

# PIPELINE 1A: только scaling + LGBM (без фичер селекции)
pipe_lgbm_base = Pipeline([
    ('scaler', StandardScaler()),
    ('lgbm', LGBMClassifier(n_estimators=100, random_state=42))
])
pipe_lgbm_base.fit(X_train, y_train)
pred_lgbm_base = pipe_lgbm_base.predict_proba(X_test)[:, 1]
auc_lgbm_base = roc_auc_score(y_test, pred_lgbm_base)
print(f'[Pipeline LGBM basic] ROC-AUC: {auc_lgbm_base:.4f}')

# PIPELINE 1B: scaling + feature selection + LGBM
# Селектор тренируется внутри пайплайна по cross-val на train (без data leakage)
pipe_lgbm_fs = Pipeline([
    ('scaler', StandardScaler()),
    ('selector', SelectFromModel(LGBMClassifier(n_estimators=100, random_state=42), threshold="median")),
    ('lgbm', LGBMClassifier(n_estimators=100, random_state=42))
])
pipe_lgbm_fs.fit(X_train, y_train)
pred_lgbm_fs = pipe_lgbm_fs.predict_proba(X_test)[:, 1]
auc_lgbm_fs = roc_auc_score(y_test, pred_lgbm_fs)
print(f'[Pipeline LGBM + feature selection] ROC-AUC: {auc_lgbm_fs:.4f}')

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


[Pipeline LGBM basic] ROC-AUC: 0.6980
[Pipeline LGBM + feature selection] ROC-AUC: 0.6742


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SelectFromModel was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SelectFromModel was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


### Собственное решение 2

In [22]:
# PIPELINE 2: CatBoost + простая обработка пропусков
pipe_catboost = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('catboost', CatBoostClassifier(iterations=200,
                                    learning_rate=0.05,
                                    eval_metric='AUC',
                                    random_state=42,
                                    verbose=0))
])

pipe_catboost.fit(X_train, y_train)
pred_cat = pipe_catboost.predict_proba(X_test)[:, 1]
auc_cat = roc_auc_score(y_test, pred_cat)
print(f'[Pipeline CatBoost] ROC-AUC: {auc_cat:.4f}')


[Pipeline CatBoost] ROC-AUC: 0.7048


~~### Собственное решение 3~~

In [23]:
# # PIPELINE 3: Logistic Regression + StandardScaler + гиперпараметры GridSearch
# pipe_logreg = Pipeline([
#     ('scaler', StandardScaler()),
#     ('logreg', LogisticRegression(max_iter=300))
# ])

# param_grid = {'logreg__C': [0.01, 0.1, 1, 3, 10]}
# grid = GridSearchCV(pipe_logreg, param_grid, scoring='roc_auc', cv=5)
# grid.fit(X_train, y_train)

# print(f"[Pipeline LogReg] Лучшее C: {grid.best_params_}")
# best_logreg = grid.best_estimator_
# preds_lr = best_logreg.predict_proba(X_test)[:, 1]
# auc_lr = roc_auc_score(y_test, preds_lr)
# print(f'[Pipeline LogReg tuned] ROC-AUC: {auc_lr:.4f}')

~~### Вывод~~
~~Свое решение оказалось лучше LAMA baseline: максимум ROC-AUC своего решения: 0.7455 (пайплайн 3), лучшего baseline: 0.7217~~


----
### [Дополнительно]

1) Исправление 1 - использовать не GridSearch для подбора параметров

In [24]:
!pip install optuna

In [35]:
import optuna
from sklearn.impute import SimpleImputer
from sklearn.metrics import make_scorer
from sklearn.model_selection import cross_val_score

In [31]:
import warnings
warnings.filterwarnings('ignore')

In [46]:
# Вариант 1
def objective(trial):
    try:
        pipe = Pipeline([
            ('imputer', SimpleImputer(strategy='mean')),
            ('scaler', StandardScaler()),
            ('lgbm', LGBMClassifier(
                n_estimators=trial.suggest_int('n_estimators', 80, 300),
                learning_rate=trial.suggest_float('learning_rate', 0.01, 0.12, log=True),
                max_depth=trial.suggest_int('max_depth', 3, 8),
                num_leaves=trial.suggest_int('num_leaves', 5, 32),
                subsample=trial.suggest_float('subsample', 0.6, 1.0),
                reg_alpha=trial.suggest_float('reg_alpha', 0.0, 3.0),
                reg_lambda=trial.suggest_float('reg_lambda', 0.0, 3.0),
                random_state=42,
                n_jobs=-1,
                verbose=-1,
            ))
        ])
        auc = cross_val_score(
            pipe,
            X_train, y_train,
            scoring=make_scorer(roc_auc_score, needs_proba=True),
            cv=5
        ).mean()
        if np.isnan(auc):
            return 0.0
        return auc
    except Exception as e:
        print(e)
        return 0.0


study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=40, show_progress_bar=True)

print("Лучшие гиперпы Optuna:", study.best_trial.params)

# Финальное обучение и тест
best_params = study.best_trial.params
pipe_optuna = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler()),
    ('lgbm', LGBMClassifier(
        **best_params,
        random_state=42,
        n_jobs=-1,
        verbose=-1,
    )),
])
pipe_optuna.fit(X_train, y_train)
pred_optuna = pipe_optuna.predict_proba(X_test)[:, 1]
auc_optuna = roc_auc_score(y_test, pred_optuna)
print(f'[Pipeline LGBM + Optuna] ROC-AUC: {auc_optuna:.4f}')


[I 2025-12-28 22:14:51,371] A new study created in memory with name: no-name-7c149ca5-82b9-46ff-9741-6b9f30e756bb
INFO:optuna.storages._in_memory:A new study created in memory with name: no-name-7c149ca5-82b9-46ff-9741-6b9f30e756bb


  0%|          | 0/40 [00:00<?, ?it/s]

INFO:optuna.study.study:Trial 0 finished with value: 0.0 and parameters: {'n_estimators': 233, 'learning_rate': 0.04104978229918572, 'max_depth': 6, 'num_leaves': 27, 'subsample': 0.8133734315144017, 'reg_alpha': 2.257040051482158, 'reg_lambda': 2.2324026442045586}. Best is trial 0 with value: 0.0.
INFO:optuna.study.study:Trial 1 finished with value: 0.0 and parameters: {'n_estimators': 106, 'learning_rate': 0.06169932093653959, 'max_depth': 3, 'num_leaves': 24, 'subsample': 0.7795293409385702, 'reg_alpha': 2.03913365026799, 'reg_lambda': 2.2734753004261856}. Best is trial 0 with value: 0.0.


[I 2025-12-28 22:14:51,574] Trial 0 finished with value: 0.0 and parameters: {'n_estimators': 233, 'learning_rate': 0.04104978229918572, 'max_depth': 6, 'num_leaves': 27, 'subsample': 0.8133734315144017, 'reg_alpha': 2.257040051482158, 'reg_lambda': 2.2324026442045586}. Best is trial 0 with value: 0.0.
[I 2025-12-28 22:14:51,711] Trial 1 finished with value: 0.0 and parameters: {'n_estimators': 106, 'learning_rate': 0.06169932093653959, 'max_depth': 3, 'num_leaves': 24, 'subsample': 0.7795293409385702, 'reg_alpha': 2.03913365026799, 'reg_lambda': 2.2734753004261856}. Best is trial 0 with value: 0.0.


INFO:optuna.study.study:Trial 2 finished with value: 0.0 and parameters: {'n_estimators': 260, 'learning_rate': 0.08994427676806044, 'max_depth': 7, 'num_leaves': 17, 'subsample': 0.7114700765295074, 'reg_alpha': 2.5138909984763336, 'reg_lambda': 2.9293134434883115}. Best is trial 0 with value: 0.0.
INFO:optuna.study.study:Trial 3 finished with value: 0.0 and parameters: {'n_estimators': 183, 'learning_rate': 0.11385929307594019, 'max_depth': 4, 'num_leaves': 8, 'subsample': 0.9207614930617725, 'reg_alpha': 0.9179984324637993, 'reg_lambda': 2.97300514051142}. Best is trial 0 with value: 0.0.


[I 2025-12-28 22:14:51,894] Trial 2 finished with value: 0.0 and parameters: {'n_estimators': 260, 'learning_rate': 0.08994427676806044, 'max_depth': 7, 'num_leaves': 17, 'subsample': 0.7114700765295074, 'reg_alpha': 2.5138909984763336, 'reg_lambda': 2.9293134434883115}. Best is trial 0 with value: 0.0.
[I 2025-12-28 22:14:52,094] Trial 3 finished with value: 0.0 and parameters: {'n_estimators': 183, 'learning_rate': 0.11385929307594019, 'max_depth': 4, 'num_leaves': 8, 'subsample': 0.9207614930617725, 'reg_alpha': 0.9179984324637993, 'reg_lambda': 2.97300514051142}. Best is trial 0 with value: 0.0.


INFO:optuna.study.study:Trial 4 finished with value: 0.0 and parameters: {'n_estimators': 238, 'learning_rate': 0.10960977639616482, 'max_depth': 7, 'num_leaves': 14, 'subsample': 0.8503544804485057, 'reg_alpha': 2.44610858017915, 'reg_lambda': 1.974551052282484}. Best is trial 0 with value: 0.0.
INFO:optuna.study.study:Trial 5 finished with value: 0.0 and parameters: {'n_estimators': 246, 'learning_rate': 0.010727574026087927, 'max_depth': 6, 'num_leaves': 5, 'subsample': 0.790774583149403, 'reg_alpha': 1.610735008605409, 'reg_lambda': 1.5479721124437376}. Best is trial 0 with value: 0.0.


[I 2025-12-28 22:14:52,263] Trial 4 finished with value: 0.0 and parameters: {'n_estimators': 238, 'learning_rate': 0.10960977639616482, 'max_depth': 7, 'num_leaves': 14, 'subsample': 0.8503544804485057, 'reg_alpha': 2.44610858017915, 'reg_lambda': 1.974551052282484}. Best is trial 0 with value: 0.0.
[I 2025-12-28 22:14:52,444] Trial 5 finished with value: 0.0 and parameters: {'n_estimators': 246, 'learning_rate': 0.010727574026087927, 'max_depth': 6, 'num_leaves': 5, 'subsample': 0.790774583149403, 'reg_alpha': 1.610735008605409, 'reg_lambda': 1.5479721124437376}. Best is trial 0 with value: 0.0.


INFO:optuna.study.study:Trial 6 finished with value: 0.0 and parameters: {'n_estimators': 110, 'learning_rate': 0.07255893812894793, 'max_depth': 5, 'num_leaves': 31, 'subsample': 0.7523436602683965, 'reg_alpha': 0.1799033920710632, 'reg_lambda': 1.6911981048925684}. Best is trial 0 with value: 0.0.


[I 2025-12-28 22:14:52,589] Trial 6 finished with value: 0.0 and parameters: {'n_estimators': 110, 'learning_rate': 0.07255893812894793, 'max_depth': 5, 'num_leaves': 31, 'subsample': 0.7523436602683965, 'reg_alpha': 0.1799033920710632, 'reg_lambda': 1.6911981048925684}. Best is trial 0 with value: 0.0.


INFO:optuna.study.study:Trial 7 finished with value: 0.0 and parameters: {'n_estimators': 254, 'learning_rate': 0.014494042565181123, 'max_depth': 5, 'num_leaves': 29, 'subsample': 0.6983699769472224, 'reg_alpha': 0.4753078309032841, 'reg_lambda': 0.9662663201020799}. Best is trial 0 with value: 0.0.


[I 2025-12-28 22:14:52,800] Trial 7 finished with value: 0.0 and parameters: {'n_estimators': 254, 'learning_rate': 0.014494042565181123, 'max_depth': 5, 'num_leaves': 29, 'subsample': 0.6983699769472224, 'reg_alpha': 0.4753078309032841, 'reg_lambda': 0.9662663201020799}. Best is trial 0 with value: 0.0.


INFO:optuna.study.study:Trial 8 finished with value: 0.0 and parameters: {'n_estimators': 259, 'learning_rate': 0.01327300257603873, 'max_depth': 6, 'num_leaves': 31, 'subsample': 0.8086148503194909, 'reg_alpha': 2.2372140254797372, 'reg_lambda': 2.8903704879755137}. Best is trial 0 with value: 0.0.
INFO:optuna.study.study:Trial 9 finished with value: 0.0 and parameters: {'n_estimators': 154, 'learning_rate': 0.016821911238205402, 'max_depth': 4, 'num_leaves': 25, 'subsample': 0.8615381798914641, 'reg_alpha': 1.275756296007744, 'reg_lambda': 0.9222311982299365}. Best is trial 0 with value: 0.0.


[I 2025-12-28 22:14:53,009] Trial 8 finished with value: 0.0 and parameters: {'n_estimators': 259, 'learning_rate': 0.01327300257603873, 'max_depth': 6, 'num_leaves': 31, 'subsample': 0.8086148503194909, 'reg_alpha': 2.2372140254797372, 'reg_lambda': 2.8903704879755137}. Best is trial 0 with value: 0.0.
[I 2025-12-28 22:14:53,179] Trial 9 finished with value: 0.0 and parameters: {'n_estimators': 154, 'learning_rate': 0.016821911238205402, 'max_depth': 4, 'num_leaves': 25, 'subsample': 0.8615381798914641, 'reg_alpha': 1.275756296007744, 'reg_lambda': 0.9222311982299365}. Best is trial 0 with value: 0.0.


INFO:optuna.study.study:Trial 10 finished with value: 0.0 and parameters: {'n_estimators': 200, 'learning_rate': 0.030462991255279202, 'max_depth': 8, 'num_leaves': 23, 'subsample': 0.613977073186419, 'reg_alpha': 2.9735538696021124, 'reg_lambda': 0.15070324452831496}. Best is trial 0 with value: 0.0.
INFO:optuna.study.study:Trial 11 finished with value: 0.0 and parameters: {'n_estimators': 80, 'learning_rate': 0.04846727279259594, 'max_depth': 3, 'num_leaves': 23, 'subsample': 0.9572859244372441, 'reg_alpha': 1.8932929011070996, 'reg_lambda': 2.2608069192305678}. Best is trial 0 with value: 0.0.


[I 2025-12-28 22:14:53,367] Trial 10 finished with value: 0.0 and parameters: {'n_estimators': 200, 'learning_rate': 0.030462991255279202, 'max_depth': 8, 'num_leaves': 23, 'subsample': 0.613977073186419, 'reg_alpha': 2.9735538696021124, 'reg_lambda': 0.15070324452831496}. Best is trial 0 with value: 0.0.
[I 2025-12-28 22:14:53,507] Trial 11 finished with value: 0.0 and parameters: {'n_estimators': 80, 'learning_rate': 0.04846727279259594, 'max_depth': 3, 'num_leaves': 23, 'subsample': 0.9572859244372441, 'reg_alpha': 1.8932929011070996, 'reg_lambda': 2.2608069192305678}. Best is trial 0 with value: 0.0.


INFO:optuna.study.study:Trial 12 finished with value: 0.0 and parameters: {'n_estimators': 138, 'learning_rate': 0.03948982935658359, 'max_depth': 3, 'num_leaves': 26, 'subsample': 0.8814703620210864, 'reg_alpha': 1.9636024734898436, 'reg_lambda': 2.357804761520325}. Best is trial 0 with value: 0.0.
INFO:optuna.study.study:Trial 13 finished with value: 0.0 and parameters: {'n_estimators': 202, 'learning_rate': 0.027045216971982, 'max_depth': 4, 'num_leaves': 19, 'subsample': 0.6698728358368133, 'reg_alpha': 2.9219992440951166, 'reg_lambda': 2.3989927230816184}. Best is trial 0 with value: 0.0.


[I 2025-12-28 22:14:53,674] Trial 12 finished with value: 0.0 and parameters: {'n_estimators': 138, 'learning_rate': 0.03948982935658359, 'max_depth': 3, 'num_leaves': 26, 'subsample': 0.8814703620210864, 'reg_alpha': 1.9636024734898436, 'reg_lambda': 2.357804761520325}. Best is trial 0 with value: 0.0.
[I 2025-12-28 22:14:53,858] Trial 13 finished with value: 0.0 and parameters: {'n_estimators': 202, 'learning_rate': 0.027045216971982, 'max_depth': 4, 'num_leaves': 19, 'subsample': 0.6698728358368133, 'reg_alpha': 2.9219992440951166, 'reg_lambda': 2.3989927230816184}. Best is trial 0 with value: 0.0.


INFO:optuna.study.study:Trial 14 finished with value: 0.0 and parameters: {'n_estimators': 297, 'learning_rate': 0.05932890274213691, 'max_depth': 7, 'num_leaves': 19, 'subsample': 0.782737671868098, 'reg_alpha': 1.5265123703170345, 'reg_lambda': 1.0603547488867278}. Best is trial 0 with value: 0.0.
INFO:optuna.study.study:Trial 15 finished with value: 0.0 and parameters: {'n_estimators': 168, 'learning_rate': 0.022097909183105387, 'max_depth': 5, 'num_leaves': 28, 'subsample': 0.9989073180379091, 'reg_alpha': 2.1231848351339417, 'reg_lambda': 2.0283479595165805}. Best is trial 0 with value: 0.0.


[I 2025-12-28 22:14:54,107] Trial 14 finished with value: 0.0 and parameters: {'n_estimators': 297, 'learning_rate': 0.05932890274213691, 'max_depth': 7, 'num_leaves': 19, 'subsample': 0.782737671868098, 'reg_alpha': 1.5265123703170345, 'reg_lambda': 1.0603547488867278}. Best is trial 0 with value: 0.0.
[I 2025-12-28 22:14:54,282] Trial 15 finished with value: 0.0 and parameters: {'n_estimators': 168, 'learning_rate': 0.022097909183105387, 'max_depth': 5, 'num_leaves': 28, 'subsample': 0.9989073180379091, 'reg_alpha': 2.1231848351339417, 'reg_lambda': 2.0283479595165805}. Best is trial 0 with value: 0.0.


INFO:optuna.study.study:Trial 16 finished with value: 0.0 and parameters: {'n_estimators': 217, 'learning_rate': 0.04554959160281099, 'max_depth': 6, 'num_leaves': 22, 'subsample': 0.8247369494090652, 'reg_alpha': 1.1764535015174855, 'reg_lambda': 2.5802341092965486}. Best is trial 0 with value: 0.0.
INFO:optuna.study.study:Trial 17 finished with value: 0.0 and parameters: {'n_estimators': 120, 'learning_rate': 0.06241970542994927, 'max_depth': 8, 'num_leaves': 13, 'subsample': 0.747864721398479, 'reg_alpha': 2.5815344777917804, 'reg_lambda': 1.8719835798258213}. Best is trial 0 with value: 0.0.


[I 2025-12-28 22:14:54,481] Trial 16 finished with value: 0.0 and parameters: {'n_estimators': 217, 'learning_rate': 0.04554959160281099, 'max_depth': 6, 'num_leaves': 22, 'subsample': 0.8247369494090652, 'reg_alpha': 1.1764535015174855, 'reg_lambda': 2.5802341092965486}. Best is trial 0 with value: 0.0.
[I 2025-12-28 22:14:54,636] Trial 17 finished with value: 0.0 and parameters: {'n_estimators': 120, 'learning_rate': 0.06241970542994927, 'max_depth': 8, 'num_leaves': 13, 'subsample': 0.747864721398479, 'reg_alpha': 2.5815344777917804, 'reg_lambda': 1.8719835798258213}. Best is trial 0 with value: 0.0.


INFO:optuna.study.study:Trial 18 finished with value: 0.0 and parameters: {'n_estimators': 296, 'learning_rate': 0.022426217366416555, 'max_depth': 3, 'num_leaves': 27, 'subsample': 0.910573264832398, 'reg_alpha': 1.7314306504271144, 'reg_lambda': 1.344239955742835}. Best is trial 0 with value: 0.0.
INFO:optuna.study.study:Trial 19 finished with value: 0.0 and parameters: {'n_estimators': 87, 'learning_rate': 0.03627848946605356, 'max_depth': 4, 'num_leaves': 32, 'subsample': 0.6196772529393308, 'reg_alpha': 2.204241638804471, 'reg_lambda': 0.4246366725183326}. Best is trial 0 with value: 0.0.


[I 2025-12-28 22:14:54,881] Trial 18 finished with value: 0.0 and parameters: {'n_estimators': 296, 'learning_rate': 0.022426217366416555, 'max_depth': 3, 'num_leaves': 27, 'subsample': 0.910573264832398, 'reg_alpha': 1.7314306504271144, 'reg_lambda': 1.344239955742835}. Best is trial 0 with value: 0.0.
[I 2025-12-28 22:14:55,023] Trial 19 finished with value: 0.0 and parameters: {'n_estimators': 87, 'learning_rate': 0.03627848946605356, 'max_depth': 4, 'num_leaves': 32, 'subsample': 0.6196772529393308, 'reg_alpha': 2.204241638804471, 'reg_lambda': 0.4246366725183326}. Best is trial 0 with value: 0.0.


INFO:optuna.study.study:Trial 20 finished with value: 0.0 and parameters: {'n_estimators': 220, 'learning_rate': 0.08043091133663754, 'max_depth': 5, 'num_leaves': 21, 'subsample': 0.761522237771771, 'reg_alpha': 2.6616493461642836, 'reg_lambda': 2.572109536107029}. Best is trial 0 with value: 0.0.
INFO:optuna.study.study:Trial 21 finished with value: 0.0 and parameters: {'n_estimators': 270, 'learning_rate': 0.0902213372420591, 'max_depth': 7, 'num_leaves': 15, 'subsample': 0.708300518784417, 'reg_alpha': 2.440875345601874, 'reg_lambda': 2.727323160999093}. Best is trial 0 with value: 0.0.


[I 2025-12-28 22:14:55,229] Trial 20 finished with value: 0.0 and parameters: {'n_estimators': 220, 'learning_rate': 0.08043091133663754, 'max_depth': 5, 'num_leaves': 21, 'subsample': 0.761522237771771, 'reg_alpha': 2.6616493461642836, 'reg_lambda': 2.572109536107029}. Best is trial 0 with value: 0.0.
[I 2025-12-28 22:14:55,419] Trial 21 finished with value: 0.0 and parameters: {'n_estimators': 270, 'learning_rate': 0.0902213372420591, 'max_depth': 7, 'num_leaves': 15, 'subsample': 0.708300518784417, 'reg_alpha': 2.440875345601874, 'reg_lambda': 2.727323160999093}. Best is trial 0 with value: 0.0.


INFO:optuna.study.study:Trial 22 finished with value: 0.0 and parameters: {'n_estimators': 279, 'learning_rate': 0.05543964735720671, 'max_depth': 7, 'num_leaves': 16, 'subsample': 0.7127658343521297, 'reg_alpha': 2.6562895037703815, 'reg_lambda': 2.1706639304384963}. Best is trial 0 with value: 0.0.
INFO:optuna.study.study:Trial 23 finished with value: 0.0 and parameters: {'n_estimators': 224, 'learning_rate': 0.0918767177366963, 'max_depth': 6, 'num_leaves': 17, 'subsample': 0.6624636085122737, 'reg_alpha': 1.9096110168154266, 'reg_lambda': 2.6994182124262234}. Best is trial 0 with value: 0.0.


[I 2025-12-28 22:14:55,616] Trial 22 finished with value: 0.0 and parameters: {'n_estimators': 279, 'learning_rate': 0.05543964735720671, 'max_depth': 7, 'num_leaves': 16, 'subsample': 0.7127658343521297, 'reg_alpha': 2.6562895037703815, 'reg_lambda': 2.1706639304384963}. Best is trial 0 with value: 0.0.
[I 2025-12-28 22:14:55,795] Trial 23 finished with value: 0.0 and parameters: {'n_estimators': 224, 'learning_rate': 0.0918767177366963, 'max_depth': 6, 'num_leaves': 17, 'subsample': 0.6624636085122737, 'reg_alpha': 1.9096110168154266, 'reg_lambda': 2.6994182124262234}. Best is trial 0 with value: 0.0.


INFO:optuna.study.study:Trial 24 finished with value: 0.0 and parameters: {'n_estimators': 234, 'learning_rate': 0.06993743796035655, 'max_depth': 8, 'num_leaves': 25, 'subsample': 0.828538907629735, 'reg_alpha': 2.2892345221809993, 'reg_lambda': 2.975409429498139}. Best is trial 0 with value: 0.0.


[I 2025-12-28 22:14:55,992] Trial 24 finished with value: 0.0 and parameters: {'n_estimators': 234, 'learning_rate': 0.06993743796035655, 'max_depth': 8, 'num_leaves': 25, 'subsample': 0.828538907629735, 'reg_alpha': 2.2892345221809993, 'reg_lambda': 2.975409429498139}. Best is trial 0 with value: 0.0.


INFO:optuna.study.study:Trial 25 finished with value: 0.0 and parameters: {'n_estimators': 181, 'learning_rate': 0.05027671076996962, 'max_depth': 7, 'num_leaves': 12, 'subsample': 0.7464531743029472, 'reg_alpha': 2.825655430588564, 'reg_lambda': 1.7628388444895107}. Best is trial 0 with value: 0.0.


[I 2025-12-28 22:14:56,198] Trial 25 finished with value: 0.0 and parameters: {'n_estimators': 181, 'learning_rate': 0.05027671076996962, 'max_depth': 7, 'num_leaves': 12, 'subsample': 0.7464531743029472, 'reg_alpha': 2.825655430588564, 'reg_lambda': 1.7628388444895107}. Best is trial 0 with value: 0.0.


INFO:optuna.study.study:Trial 26 finished with value: 0.0 and parameters: {'n_estimators': 267, 'learning_rate': 0.041135530717982344, 'max_depth': 6, 'num_leaves': 21, 'subsample': 0.6635017364478576, 'reg_alpha': 2.0730906681248813, 'reg_lambda': 2.4722253442850133}. Best is trial 0 with value: 0.0.
INFO:optuna.study.study:Trial 27 finished with value: 0.0 and parameters: {'n_estimators': 205, 'learning_rate': 0.09510761745182905, 'max_depth': 7, 'num_leaves': 11, 'subsample': 0.726487838451462, 'reg_alpha': 1.7487821837600381, 'reg_lambda': 2.138771341034687}. Best is trial 0 with value: 0.0.


[I 2025-12-28 22:14:56,408] Trial 26 finished with value: 0.0 and parameters: {'n_estimators': 267, 'learning_rate': 0.041135530717982344, 'max_depth': 6, 'num_leaves': 21, 'subsample': 0.6635017364478576, 'reg_alpha': 2.0730906681248813, 'reg_lambda': 2.4722253442850133}. Best is trial 0 with value: 0.0.
[I 2025-12-28 22:14:56,583] Trial 27 finished with value: 0.0 and parameters: {'n_estimators': 205, 'learning_rate': 0.09510761745182905, 'max_depth': 7, 'num_leaves': 11, 'subsample': 0.726487838451462, 'reg_alpha': 1.7487821837600381, 'reg_lambda': 2.138771341034687}. Best is trial 0 with value: 0.0.


INFO:optuna.study.study:Trial 28 finished with value: 0.0 and parameters: {'n_estimators': 279, 'learning_rate': 0.06840104791254006, 'max_depth': 6, 'num_leaves': 18, 'subsample': 0.7775821601093627, 'reg_alpha': 2.420583861890232, 'reg_lambda': 1.2514715614914824}. Best is trial 0 with value: 0.0.
INFO:optuna.study.study:Trial 29 finished with value: 0.0 and parameters: {'n_estimators': 188, 'learning_rate': 0.11240132351952561, 'max_depth': 5, 'num_leaves': 29, 'subsample': 0.9131655135445215, 'reg_alpha': 1.2786010562441108, 'reg_lambda': 2.8012274086952784}. Best is trial 0 with value: 0.0.


[I 2025-12-28 22:14:56,780] Trial 28 finished with value: 0.0 and parameters: {'n_estimators': 279, 'learning_rate': 0.06840104791254006, 'max_depth': 6, 'num_leaves': 18, 'subsample': 0.7775821601093627, 'reg_alpha': 2.420583861890232, 'reg_lambda': 1.2514715614914824}. Best is trial 0 with value: 0.0.
[I 2025-12-28 22:14:56,975] Trial 29 finished with value: 0.0 and parameters: {'n_estimators': 188, 'learning_rate': 0.11240132351952561, 'max_depth': 5, 'num_leaves': 29, 'subsample': 0.9131655135445215, 'reg_alpha': 1.2786010562441108, 'reg_lambda': 2.8012274086952784}. Best is trial 0 with value: 0.0.


INFO:optuna.study.study:Trial 30 finished with value: 0.0 and parameters: {'n_estimators': 140, 'learning_rate': 0.029989403828484362, 'max_depth': 8, 'num_leaves': 24, 'subsample': 0.8050159546727395, 'reg_alpha': 2.606296789896161, 'reg_lambda': 2.284991723491604}. Best is trial 0 with value: 0.0.


[I 2025-12-28 22:14:57,147] Trial 30 finished with value: 0.0 and parameters: {'n_estimators': 140, 'learning_rate': 0.029989403828484362, 'max_depth': 8, 'num_leaves': 24, 'subsample': 0.8050159546727395, 'reg_alpha': 2.606296789896161, 'reg_lambda': 2.284991723491604}. Best is trial 0 with value: 0.0.


INFO:optuna.study.study:Trial 31 finished with value: 0.0 and parameters: {'n_estimators': 243, 'learning_rate': 0.115596612384314, 'max_depth': 4, 'num_leaves': 8, 'subsample': 0.8649296953727504, 'reg_alpha': 0.8429592526750358, 'reg_lambda': 2.9898193178966324}. Best is trial 0 with value: 0.0.


[I 2025-12-28 22:14:57,384] Trial 31 finished with value: 0.0 and parameters: {'n_estimators': 243, 'learning_rate': 0.115596612384314, 'max_depth': 4, 'num_leaves': 8, 'subsample': 0.8649296953727504, 'reg_alpha': 0.8429592526750358, 'reg_lambda': 2.9898193178966324}. Best is trial 0 with value: 0.0.


INFO:optuna.study.study:Trial 32 finished with value: 0.0 and parameters: {'n_estimators': 232, 'learning_rate': 0.09989617844165112, 'max_depth': 3, 'num_leaves': 9, 'subsample': 0.9037640316593566, 'reg_alpha': 0.8664186343029319, 'reg_lambda': 2.669049553586606}. Best is trial 0 with value: 0.0.
INFO:optuna.study.study:Trial 33 finished with value: 0.0 and parameters: {'n_estimators': 105, 'learning_rate': 0.08777175537496529, 'max_depth': 4, 'num_leaves': 6, 'subsample': 0.9641078264171616, 'reg_alpha': 0.7223300078066884, 'reg_lambda': 1.970944592304672}. Best is trial 0 with value: 0.0.


[I 2025-12-28 22:14:57,588] Trial 32 finished with value: 0.0 and parameters: {'n_estimators': 232, 'learning_rate': 0.09989617844165112, 'max_depth': 3, 'num_leaves': 9, 'subsample': 0.9037640316593566, 'reg_alpha': 0.8664186343029319, 'reg_lambda': 2.669049553586606}. Best is trial 0 with value: 0.0.
[I 2025-12-28 22:14:57,740] Trial 33 finished with value: 0.0 and parameters: {'n_estimators': 105, 'learning_rate': 0.08777175537496529, 'max_depth': 4, 'num_leaves': 6, 'subsample': 0.9641078264171616, 'reg_alpha': 0.7223300078066884, 'reg_lambda': 1.970944592304672}. Best is trial 0 with value: 0.0.


INFO:optuna.study.study:Trial 34 finished with value: 0.0 and parameters: {'n_estimators': 171, 'learning_rate': 0.07834727329316223, 'max_depth': 3, 'num_leaves': 9, 'subsample': 0.8424655966493292, 'reg_alpha': 0.1571558003183171, 'reg_lambda': 2.4913023186565186}. Best is trial 0 with value: 0.0.


[I 2025-12-28 22:14:57,922] Trial 34 finished with value: 0.0 and parameters: {'n_estimators': 171, 'learning_rate': 0.07834727329316223, 'max_depth': 3, 'num_leaves': 9, 'subsample': 0.8424655966493292, 'reg_alpha': 0.1571558003183171, 'reg_lambda': 2.4913023186565186}. Best is trial 0 with value: 0.0.


INFO:optuna.study.study:Trial 35 finished with value: 0.0 and parameters: {'n_estimators': 251, 'learning_rate': 0.11645505159588118, 'max_depth': 5, 'num_leaves': 29, 'subsample': 0.727471117042364, 'reg_alpha': 1.0323464754448128, 'reg_lambda': 2.796971929623157}. Best is trial 0 with value: 0.0.
INFO:optuna.study.study:Trial 36 finished with value: 0.0 and parameters: {'n_estimators': 123, 'learning_rate': 0.05535898792383328, 'max_depth': 4, 'num_leaves': 6, 'subsample': 0.688925778608202, 'reg_alpha': 0.6098601149617151, 'reg_lambda': 1.7046531084897256}. Best is trial 0 with value: 0.0.


[I 2025-12-28 22:14:58,147] Trial 35 finished with value: 0.0 and parameters: {'n_estimators': 251, 'learning_rate': 0.11645505159588118, 'max_depth': 5, 'num_leaves': 29, 'subsample': 0.727471117042364, 'reg_alpha': 1.0323464754448128, 'reg_lambda': 2.796971929623157}. Best is trial 0 with value: 0.0.
[I 2025-12-28 22:14:58,320] Trial 36 finished with value: 0.0 and parameters: {'n_estimators': 123, 'learning_rate': 0.05535898792383328, 'max_depth': 4, 'num_leaves': 6, 'subsample': 0.688925778608202, 'reg_alpha': 0.6098601149617151, 'reg_lambda': 1.7046531084897256}. Best is trial 0 with value: 0.0.


INFO:optuna.study.study:Trial 37 finished with value: 0.0 and parameters: {'n_estimators': 143, 'learning_rate': 0.07890427662786581, 'max_depth': 6, 'num_leaves': 20, 'subsample': 0.9480156745077905, 'reg_alpha': 2.3006448962505277, 'reg_lambda': 2.8438094361398107}. Best is trial 0 with value: 0.0.
INFO:optuna.study.study:Trial 38 finished with value: 0.0 and parameters: {'n_estimators': 97, 'learning_rate': 0.10358610143005223, 'max_depth': 3, 'num_leaves': 14, 'subsample': 0.794964815979305, 'reg_alpha': 0.4160280916826028, 'reg_lambda': 0.6227290520690993}. Best is trial 0 with value: 0.0.


[I 2025-12-28 22:14:58,498] Trial 37 finished with value: 0.0 and parameters: {'n_estimators': 143, 'learning_rate': 0.07890427662786581, 'max_depth': 6, 'num_leaves': 20, 'subsample': 0.9480156745077905, 'reg_alpha': 2.3006448962505277, 'reg_lambda': 2.8438094361398107}. Best is trial 0 with value: 0.0.
[I 2025-12-28 22:14:58,649] Trial 38 finished with value: 0.0 and parameters: {'n_estimators': 97, 'learning_rate': 0.10358610143005223, 'max_depth': 3, 'num_leaves': 14, 'subsample': 0.794964815979305, 'reg_alpha': 0.4160280916826028, 'reg_lambda': 0.6227290520690993}. Best is trial 0 with value: 0.0.


INFO:optuna.study.study:Trial 39 finished with value: 0.0 and parameters: {'n_estimators': 262, 'learning_rate': 0.0647717216495692, 'max_depth': 7, 'num_leaves': 30, 'subsample': 0.7688217738410504, 'reg_alpha': 1.4384348634334865, 'reg_lambda': 1.5609845004426663}. Best is trial 0 with value: 0.0.


[I 2025-12-28 22:14:58,877] Trial 39 finished with value: 0.0 and parameters: {'n_estimators': 262, 'learning_rate': 0.0647717216495692, 'max_depth': 7, 'num_leaves': 30, 'subsample': 0.7688217738410504, 'reg_alpha': 1.4384348634334865, 'reg_lambda': 1.5609845004426663}. Best is trial 0 with value: 0.0.
Лучшие гиперпы Optuna: {'n_estimators': 233, 'learning_rate': 0.04104978229918572, 'max_depth': 6, 'num_leaves': 27, 'subsample': 0.8133734315144017, 'reg_alpha': 2.257040051482158, 'reg_lambda': 2.2324026442045586}
[Pipeline LGBM + Optuna] ROC-AUC: 0.6776


In [52]:
# Вариант 2
cv_strategy = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

def objective_lr(trial):
    c_value = trial.suggest_float("C", 1e-1, 10.0, log=True)

    solver = trial.suggest_categorical("solver", ["liblinear", "lbfgs"])
    if solver == "liblinear":
        penalty = trial.suggest_categorical("penalty", ["l1", "l2"])
    else:
        penalty = "l2"

    pipe = Pipeline([
        ('scaler', StandardScaler()),
        ('logreg', LogisticRegression(
            C=c_value,
            solver=solver,
            penalty=penalty,
            max_iter=1000,
            random_state=42
        ))
    ])

    roc_auc = cross_val_score(pipe, X_train, y_train, cv=cv_strategy, scoring="roc_auc").mean()
    return roc_auc

optuna.logging.set_verbosity(optuna.logging.INFO)
study_lr = optuna.create_study(direction="maximize")
study_lr.optimize(objective_lr, n_trials=50, show_progress_bar=True)

print(f"Лучший ROC-AUC (CV): {study_lr.best_value:.4f}")
print("Лучшие гиперпы Optuna:", study_lr.best_params)

# Финальное обучение и тест
best_params = study_lr.best_params

final_solver = best_params['solver']
final_penalty = best_params.get('penalty', 'l2')

pipe_final_lr = Pipeline([
    ('scaler', StandardScaler()),
    ('logreg', LogisticRegression(
        C=best_params['C'],
        solver=final_solver,
        penalty=final_penalty,
        max_iter=1000,
        random_state=42
    ))
])

pipe_final_lr.fit(X_train, y_train)
pred_final_lr = pipe_final_lr.predict_proba(X_test)[:, 1]
auc_final_lr = roc_auc_score(y_test, pred_final_lr)

print("-" * 40)
print(f'[Pipeline LogReg + Optuna] ROC-AUC: {auc_final_lr:.4f}')
print("-" * 40)

[I 2025-12-28 22:19:44,128] A new study created in memory with name: no-name-fd698e50-ef3e-461e-a635-2ff5f5b8fc88
INFO:optuna.storages._in_memory:A new study created in memory with name: no-name-fd698e50-ef3e-461e-a635-2ff5f5b8fc88


  0%|          | 0/50 [00:00<?, ?it/s]

INFO:optuna.study.study:Trial 0 finished with value: 0.6018745143745143 and parameters: {'C': 2.2828178361498486, 'solver': 'lbfgs'}. Best is trial 0 with value: 0.6018745143745143.
INFO:optuna.study.study:Trial 1 finished with value: 0.6229312354312354 and parameters: {'C': 0.10486052567515372, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 1 with value: 0.6229312354312354.
INFO:optuna.study.study:Trial 2 finished with value: 0.600475912975913 and parameters: {'C': 2.6056514497797334, 'solver': 'lbfgs'}. Best is trial 1 with value: 0.6229312354312354.


[I 2025-12-28 22:19:44,234] Trial 0 finished with value: 0.6018745143745143 and parameters: {'C': 2.2828178361498486, 'solver': 'lbfgs'}. Best is trial 0 with value: 0.6018745143745143.
[I 2025-12-28 22:19:44,301] Trial 1 finished with value: 0.6229312354312354 and parameters: {'C': 0.10486052567515372, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 1 with value: 0.6229312354312354.
[I 2025-12-28 22:19:44,387] Trial 2 finished with value: 0.600475912975913 and parameters: {'C': 2.6056514497797334, 'solver': 'lbfgs'}. Best is trial 1 with value: 0.6229312354312354.


INFO:optuna.study.study:Trial 3 finished with value: 0.6005147630147631 and parameters: {'C': 0.4598553428370276, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 1 with value: 0.6229312354312354.
INFO:optuna.study.study:Trial 4 finished with value: 0.6074980574980575 and parameters: {'C': 0.26836138719869695, 'solver': 'lbfgs'}. Best is trial 1 with value: 0.6229312354312354.
INFO:optuna.study.study:Trial 5 finished with value: 0.5713772338772338 and parameters: {'C': 0.3225540897159633, 'solver': 'liblinear', 'penalty': 'l1'}. Best is trial 1 with value: 0.6229312354312354.


[I 2025-12-28 22:19:44,464] Trial 3 finished with value: 0.6005147630147631 and parameters: {'C': 0.4598553428370276, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 1 with value: 0.6229312354312354.
[I 2025-12-28 22:19:44,541] Trial 4 finished with value: 0.6074980574980575 and parameters: {'C': 0.26836138719869695, 'solver': 'lbfgs'}. Best is trial 1 with value: 0.6229312354312354.
[I 2025-12-28 22:19:44,635] Trial 5 finished with value: 0.5713772338772338 and parameters: {'C': 0.3225540897159633, 'solver': 'liblinear', 'penalty': 'l1'}. Best is trial 1 with value: 0.6229312354312354.


INFO:optuna.study.study:Trial 6 finished with value: 0.5962995337995338 and parameters: {'C': 4.058452533010753, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 1 with value: 0.6229312354312354.
INFO:optuna.study.study:Trial 7 finished with value: 0.59489121989122 and parameters: {'C': 0.7852971350839549, 'solver': 'lbfgs'}. Best is trial 1 with value: 0.6229312354312354.
INFO:optuna.study.study:Trial 8 finished with value: 0.6032828282828283 and parameters: {'C': 1.2058639715147743, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 1 with value: 0.6229312354312354.


[I 2025-12-28 22:19:44,695] Trial 6 finished with value: 0.5962995337995338 and parameters: {'C': 4.058452533010753, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 1 with value: 0.6229312354312354.
[I 2025-12-28 22:19:44,778] Trial 7 finished with value: 0.59489121989122 and parameters: {'C': 0.7852971350839549, 'solver': 'lbfgs'}. Best is trial 1 with value: 0.6229312354312354.
[I 2025-12-28 22:19:44,840] Trial 8 finished with value: 0.6032828282828283 and parameters: {'C': 1.2058639715147743, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 1 with value: 0.6229312354312354.


INFO:optuna.study.study:Trial 9 finished with value: 0.5976981351981352 and parameters: {'C': 3.1025445255440296, 'solver': 'lbfgs'}. Best is trial 1 with value: 0.6229312354312354.
INFO:optuna.study.study:Trial 10 finished with value: 0.5895687645687646 and parameters: {'C': 0.20159401766444657, 'solver': 'liblinear', 'penalty': 'l1'}. Best is trial 1 with value: 0.6229312354312354.
INFO:optuna.study.study:Trial 11 finished with value: 0.6201437451437452 and parameters: {'C': 0.10001586037729449, 'solver': 'lbfgs'}. Best is trial 1 with value: 0.6229312354312354.


[I 2025-12-28 22:19:44,935] Trial 9 finished with value: 0.5976981351981352 and parameters: {'C': 3.1025445255440296, 'solver': 'lbfgs'}. Best is trial 1 with value: 0.6229312354312354.
[I 2025-12-28 22:19:45,009] Trial 10 finished with value: 0.5895687645687646 and parameters: {'C': 0.20159401766444657, 'solver': 'liblinear', 'penalty': 'l1'}. Best is trial 1 with value: 0.6229312354312354.
[I 2025-12-28 22:19:45,099] Trial 11 finished with value: 0.6201437451437452 and parameters: {'C': 0.10001586037729449, 'solver': 'lbfgs'}. Best is trial 1 with value: 0.6229312354312354.


INFO:optuna.study.study:Trial 12 finished with value: 0.6215423465423465 and parameters: {'C': 0.101392026110609, 'solver': 'lbfgs'}. Best is trial 1 with value: 0.6229312354312354.
INFO:optuna.study.study:Trial 13 finished with value: 0.6215326340326339 and parameters: {'C': 0.10698341271925699, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 1 with value: 0.6229312354312354.
INFO:optuna.study.study:Trial 14 finished with value: 0.6159382284382284 and parameters: {'C': 0.1725328086549193, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 1 with value: 0.6229312354312354.


[I 2025-12-28 22:19:45,178] Trial 12 finished with value: 0.6215423465423465 and parameters: {'C': 0.101392026110609, 'solver': 'lbfgs'}. Best is trial 1 with value: 0.6229312354312354.
[I 2025-12-28 22:19:45,261] Trial 13 finished with value: 0.6215326340326339 and parameters: {'C': 0.10698341271925699, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 1 with value: 0.6229312354312354.
[I 2025-12-28 22:19:45,322] Trial 14 finished with value: 0.6159382284382284 and parameters: {'C': 0.1725328086549193, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 1 with value: 0.6229312354312354.


INFO:optuna.study.study:Trial 15 finished with value: 0.5962898212898213 and parameters: {'C': 7.828007765078882, 'solver': 'lbfgs'}. Best is trial 1 with value: 0.6229312354312354.
INFO:optuna.study.study:Trial 16 finished with value: 0.622940947940948 and parameters: {'C': 0.8190030071607937, 'solver': 'liblinear', 'penalty': 'l1'}. Best is trial 16 with value: 0.622940947940948.
INFO:optuna.study.study:Trial 17 finished with value: 0.6201437451437452 and parameters: {'C': 0.8675097035419471, 'solver': 'liblinear', 'penalty': 'l1'}. Best is trial 16 with value: 0.622940947940948.
INFO:optuna.study.study:Trial 18 finished with value: 0.6132187257187258 and parameters: {'C': 0.5719154699219924, 'solver': 'liblinear', 'penalty': 'l1'}. Best is trial 16 with value: 0.622940947940948.


[I 2025-12-28 22:19:45,417] Trial 15 finished with value: 0.5962898212898213 and parameters: {'C': 7.828007765078882, 'solver': 'lbfgs'}. Best is trial 1 with value: 0.6229312354312354.
[I 2025-12-28 22:19:45,484] Trial 16 finished with value: 0.622940947940948 and parameters: {'C': 0.8190030071607937, 'solver': 'liblinear', 'penalty': 'l1'}. Best is trial 16 with value: 0.622940947940948.
[I 2025-12-28 22:19:45,557] Trial 17 finished with value: 0.6201437451437452 and parameters: {'C': 0.8675097035419471, 'solver': 'liblinear', 'penalty': 'l1'}. Best is trial 16 with value: 0.622940947940948.
[I 2025-12-28 22:19:45,608] Trial 18 finished with value: 0.6132187257187258 and parameters: {'C': 0.5719154699219924, 'solver': 'liblinear', 'penalty': 'l1'}. Best is trial 16 with value: 0.622940947940948.


INFO:optuna.study.study:Trial 19 finished with value: 0.6047299922299922 and parameters: {'C': 1.4133889113522586, 'solver': 'liblinear', 'penalty': 'l1'}. Best is trial 16 with value: 0.622940947940948.
INFO:optuna.study.study:Trial 20 finished with value: 0.59489121989122 and parameters: {'C': 9.17232010391545, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 16 with value: 0.622940947940948.
INFO:optuna.study.study:Trial 21 finished with value: 0.6173465423465423 and parameters: {'C': 0.1502648326319266, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.


[I 2025-12-28 22:19:45,685] Trial 19 finished with value: 0.6047299922299922 and parameters: {'C': 1.4133889113522586, 'solver': 'liblinear', 'penalty': 'l1'}. Best is trial 16 with value: 0.622940947940948.
[I 2025-12-28 22:19:45,739] Trial 20 finished with value: 0.59489121989122 and parameters: {'C': 9.17232010391545, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 16 with value: 0.622940947940948.
[I 2025-12-28 22:19:45,826] Trial 21 finished with value: 0.6173465423465423 and parameters: {'C': 0.1502648326319266, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.


INFO:optuna.study.study:Trial 22 finished with value: 0.5797397047397047 and parameters: {'C': 0.3730398951602295, 'solver': 'liblinear', 'penalty': 'l1'}. Best is trial 16 with value: 0.622940947940948.
INFO:optuna.study.study:Trial 23 finished with value: 0.6116938616938616 and parameters: {'C': 0.22540985393154225, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.
INFO:optuna.study.study:Trial 24 finished with value: 0.6187451437451437 and parameters: {'C': 0.13161235996897305, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 16 with value: 0.622940947940948.


[I 2025-12-28 22:19:45,895] Trial 22 finished with value: 0.5797397047397047 and parameters: {'C': 0.3730398951602295, 'solver': 'liblinear', 'penalty': 'l1'}. Best is trial 16 with value: 0.622940947940948.
[I 2025-12-28 22:19:45,984] Trial 23 finished with value: 0.6116938616938616 and parameters: {'C': 0.22540985393154225, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.
[I 2025-12-28 22:19:46,055] Trial 24 finished with value: 0.6187451437451437 and parameters: {'C': 0.13161235996897305, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 16 with value: 0.622940947940948.


INFO:optuna.study.study:Trial 25 finished with value: 0.6104409479409479 and parameters: {'C': 0.565092538482963, 'solver': 'liblinear', 'penalty': 'l1'}. Best is trial 16 with value: 0.622940947940948.
INFO:optuna.study.study:Trial 26 finished with value: 0.5976981351981353 and parameters: {'C': 5.394365641738605, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.
INFO:optuna.study.study:Trial 27 finished with value: 0.6033411033411034 and parameters: {'C': 1.5573645592949485, 'solver': 'liblinear', 'penalty': 'l1'}. Best is trial 16 with value: 0.622940947940948.


[I 2025-12-28 22:19:46,128] Trial 25 finished with value: 0.6104409479409479 and parameters: {'C': 0.565092538482963, 'solver': 'liblinear', 'penalty': 'l1'}. Best is trial 16 with value: 0.622940947940948.
[I 2025-12-28 22:19:46,215] Trial 26 finished with value: 0.5976981351981353 and parameters: {'C': 5.394365641738605, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.
[I 2025-12-28 22:19:46,293] Trial 27 finished with value: 0.6033411033411034 and parameters: {'C': 1.5573645592949485, 'solver': 'liblinear', 'penalty': 'l1'}. Best is trial 16 with value: 0.622940947940948.


INFO:optuna.study.study:Trial 28 finished with value: 0.6173465423465423 and parameters: {'C': 0.1428926759170521, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.
INFO:optuna.study.study:Trial 29 finished with value: 0.6032634032634033 and parameters: {'C': 1.8345176549480382, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.
INFO:optuna.study.study:Trial 30 finished with value: 0.6088966588966589 and parameters: {'C': 0.25660864842345377, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 16 with value: 0.622940947940948.


[I 2025-12-28 22:19:46,385] Trial 28 finished with value: 0.6173465423465423 and parameters: {'C': 0.1428926759170521, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.
[I 2025-12-28 22:19:46,480] Trial 29 finished with value: 0.6032634032634033 and parameters: {'C': 1.8345176549480382, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.
[I 2025-12-28 22:19:46,549] Trial 30 finished with value: 0.6088966588966589 and parameters: {'C': 0.25660864842345377, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 16 with value: 0.622940947940948.


INFO:optuna.study.study:Trial 31 finished with value: 0.6201437451437452 and parameters: {'C': 0.10197870410583686, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 16 with value: 0.622940947940948.
INFO:optuna.study.study:Trial 32 finished with value: 0.6173465423465423 and parameters: {'C': 0.12051267645844606, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 16 with value: 0.622940947940948.
INFO:optuna.study.study:Trial 33 finished with value: 0.6159285159285159 and parameters: {'C': 0.18414925280021505, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 16 with value: 0.622940947940948.
INFO:optuna.study.study:Trial 34 finished with value: 0.6019230769230769 and parameters: {'C': 0.35775376967439293, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 16 with value: 0.622940947940948.


[I 2025-12-28 22:19:46,622] Trial 31 finished with value: 0.6201437451437452 and parameters: {'C': 0.10197870410583686, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 16 with value: 0.622940947940948.
[I 2025-12-28 22:19:46,681] Trial 32 finished with value: 0.6173465423465423 and parameters: {'C': 0.12051267645844606, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 16 with value: 0.622940947940948.
[I 2025-12-28 22:19:46,748] Trial 33 finished with value: 0.6159285159285159 and parameters: {'C': 0.18414925280021505, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 16 with value: 0.622940947940948.
[I 2025-12-28 22:19:46,803] Trial 34 finished with value: 0.6019230769230769 and parameters: {'C': 0.35775376967439293, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 16 with value: 0.622940947940948.


INFO:optuna.study.study:Trial 35 finished with value: 0.6173465423465423 and parameters: {'C': 0.11928675819987851, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 16 with value: 0.622940947940948.
INFO:optuna.study.study:Trial 36 finished with value: 0.6102855477855478 and parameters: {'C': 0.27656564595161437, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.
INFO:optuna.study.study:Trial 37 finished with value: 0.5936868686868687 and parameters: {'C': 0.469746405550566, 'solver': 'liblinear', 'penalty': 'l1'}. Best is trial 16 with value: 0.622940947940948.


[I 2025-12-28 22:19:46,869] Trial 35 finished with value: 0.6173465423465423 and parameters: {'C': 0.11928675819987851, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 16 with value: 0.622940947940948.
[I 2025-12-28 22:19:46,949] Trial 36 finished with value: 0.6102855477855478 and parameters: {'C': 0.27656564595161437, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.
[I 2025-12-28 22:19:47,038] Trial 37 finished with value: 0.5936868686868687 and parameters: {'C': 0.469746405550566, 'solver': 'liblinear', 'penalty': 'l1'}. Best is trial 16 with value: 0.622940947940948.


INFO:optuna.study.study:Trial 38 finished with value: 0.6173368298368298 and parameters: {'C': 0.16105093428866407, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 16 with value: 0.622940947940948.
INFO:optuna.study.study:Trial 39 finished with value: 0.6117035742035742 and parameters: {'C': 0.21853301207142953, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.
INFO:optuna.study.study:Trial 40 finished with value: 0.600475912975913 and parameters: {'C': 2.457351116914246, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 16 with value: 0.622940947940948.


[I 2025-12-28 22:19:47,105] Trial 38 finished with value: 0.6173368298368298 and parameters: {'C': 0.16105093428866407, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 16 with value: 0.622940947940948.
[I 2025-12-28 22:19:47,190] Trial 39 finished with value: 0.6117035742035742 and parameters: {'C': 0.21853301207142953, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.
[I 2025-12-28 22:19:47,268] Trial 40 finished with value: 0.600475912975913 and parameters: {'C': 2.457351116914246, 'solver': 'liblinear', 'penalty': 'l2'}. Best is trial 16 with value: 0.622940947940948.


INFO:optuna.study.study:Trial 41 finished with value: 0.6229312354312354 and parameters: {'C': 0.10555422036863131, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.
INFO:optuna.study.study:Trial 42 finished with value: 0.6215423465423465 and parameters: {'C': 0.1010188769357931, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.
INFO:optuna.study.study:Trial 43 finished with value: 0.6173465423465423 and parameters: {'C': 0.13364639135429332, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.


[I 2025-12-28 22:19:47,363] Trial 41 finished with value: 0.6229312354312354 and parameters: {'C': 0.10555422036863131, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.
[I 2025-12-28 22:19:47,442] Trial 42 finished with value: 0.6215423465423465 and parameters: {'C': 0.1010188769357931, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.
[I 2025-12-28 22:19:47,530] Trial 43 finished with value: 0.6173465423465423 and parameters: {'C': 0.13364639135429332, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.


INFO:optuna.study.study:Trial 44 finished with value: 0.6159285159285159 and parameters: {'C': 0.18016125102021155, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.
INFO:optuna.study.study:Trial 45 finished with value: 0.6215423465423465 and parameters: {'C': 0.10288251394172904, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.


[I 2025-12-28 22:19:47,607] Trial 44 finished with value: 0.6159285159285159 and parameters: {'C': 0.18016125102021155, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.
[I 2025-12-28 22:19:47,694] Trial 45 finished with value: 0.6215423465423465 and parameters: {'C': 0.10288251394172904, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.
[I 2025-12-28 22:19:47,808] Trial 46 finished with value: 0.5962995337995338 and parameters: {'C': 3.8924064503994, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.


INFO:optuna.study.study:Trial 46 finished with value: 0.5962995337995338 and parameters: {'C': 3.8924064503994, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.
INFO:optuna.study.study:Trial 47 finished with value: 0.5976884226884227 and parameters: {'C': 1.091616330414342, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.
INFO:optuna.study.study:Trial 48 finished with value: 0.6159479409479409 and parameters: {'C': 0.15266670294821644, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.
INFO:optuna.study.study:Trial 49 finished with value: 0.6088966588966589 and parameters: {'C': 0.28553345541494946, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.


[I 2025-12-28 22:19:47,911] Trial 47 finished with value: 0.5976884226884227 and parameters: {'C': 1.091616330414342, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.
[I 2025-12-28 22:19:47,994] Trial 48 finished with value: 0.6159479409479409 and parameters: {'C': 0.15266670294821644, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.
[I 2025-12-28 22:19:48,090] Trial 49 finished with value: 0.6088966588966589 and parameters: {'C': 0.28553345541494946, 'solver': 'lbfgs'}. Best is trial 16 with value: 0.622940947940948.
Лучший ROC-AUC (CV): 0.6229
Лучшие гиперпы Optuna: {'C': 0.8190030071607937, 'solver': 'liblinear', 'penalty': 'l1'}
----------------------------------------
[Pipeline LogReg + Optuna] ROC-AUC: 0.7274
----------------------------------------


In [28]:
from sklearn.model_selection import RandomizedSearchCV

# Вариант 3 - пробуем RandomSearch
pipe = Pipeline([
    ('scaler', StandardScaler()),
    # ('pca', PCA(n_components=0.95)),
    ('lgbm', LGBMClassifier(verbose=-1, random_state=42))
])

param_dist = {
    'lgbm__n_estimators': randint(100, 500),
    'lgbm__learning_rate': uniform(0.01, 0.1),
    'lgbm__max_depth': randint(3, 7),
    'lgbm__num_leaves': randint(5, 20),
    'lgbm__subsample': uniform(0.6, 0.4),
    'lgbm__reg_alpha': uniform(0, 5),
    'lgbm__reg_lambda': uniform(0, 5)
}

rs = RandomizedSearchCV(
    estimator=pipe,
    param_distributions=param_dist,
    n_iter=50,
    scoring='roc_auc',
    cv=5
    # random_state=42,
    # n_jobs=-1
)

rs.fit(X_train, y_train)
print(f"Best params: {rs.best_params_}")
best_model = rs.best_estimator_
preds_tuned = best_model.predict_proba(X_test)[:, 1]
auc_tuned = roc_auc_score(y_test, preds_tuned)
print(f'[Pipeline LGBM + RandomSearch] ROC-AUC: {auc_tuned:.4f}')

Best params: {'lgbm__learning_rate': np.float64(0.021586905952512975), 'lgbm__max_depth': 5, 'lgbm__n_estimators': 300, 'lgbm__num_leaves': 12, 'lgbm__reg_alpha': np.float64(2.247253370691017), 'lgbm__reg_lambda': np.float64(0.47705058245205656), 'lgbm__subsample': np.float64(0.7483273008793065)}
[Pipeline LGBM + RandomSearch] ROC-AUC: 0.6810


**Вывод:** `Pipeline LogReg + Optuna` дали результат, бьющий бейзлайн - 0.7274 vs 0.7217

2) Проблема 2 - пофильтерить коррелирующие фичи

In [32]:
def remove_highcorr_features(x, threshold):
    corr_matrix = x.corr().abs()
    upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
    to_drop = [column for column in upper.columns if any(upper[column] > threshold)]

    print(f"Dropping {len(to_drop)} correlated features: {to_drop}")
    return x.drop(columns=to_drop), to_drop

X_train_uncorr, dropped_cols = remove_highcorr_features(X_train, 0.80)
X_test_uncorr = X_test.drop(columns=dropped_cols)

print(f"Cleaned train shape: {X_train_uncorr.shape}")

pipe_uncorr = Pipeline([
    ('scaler', StandardScaler()),
    ('logreg', LogisticRegression(max_iter=300, C=1.0))
])

pipe_uncorr.fit(X_train_uncorr, y_train)
pred_uncorr = pipe_uncorr.predict_proba(X_test_uncorr)[:, 1]
auc_uncorr = roc_auc_score(y_test, pred_uncorr)
print(f'\n[Alternative solution: NO correlation] ROC-AUC: {auc_uncorr:.4f}')
print("-" * 10)


Dropping 4 correlated features: ['f4_p300', 'p4_p300', 'p8_p300', 'o2_p300']
Cleaned train shape: (120, 15)

[Alternative solution: NO correlation] ROC-AUC: 0.7387
----------


**Вывод:** в EDA писала о специфике ЭЭГ данных и что 19 каналов для этого домена - мало и для определения отклонения от нормы нужно смотреть на аномалии - вышло так, что после удаления признаков с коррелацией более 80% ROC-AUC опустился с >0.74 до 0.7387 при том же решении.

3) Проблема 3 - странности результатов я думаю связаны в первую очередь с тем, что данных очень мало, медицинские данные редки и как правило довольно шумны.

In [33]:
from sklearn.ensemble import VotingClassifier, RandomForestClassifier
from sklearn.svm import SVC
from sklearn.decomposition import PCA

# лимитим max_depth и num_leaves
# добавила PCA - полезно для EEG и заодно полечит корреляционность

pipe_lgbm_constrained = Pipeline([
    ('scaler', StandardScaler()),
    ('pca', PCA(n_components=0.95)),
    ('lgbm', LGBMClassifier(
        n_estimators=200,
        learning_rate=0.03,   # помедленнее обучение
        num_leaves=7,         # малое количество
        max_depth=3,          # низкая граница
        reg_alpha=1,
        reg_lambda=1,
        random_state=42,
        verbose=-1
    ))
])

pipe_lgbm_constrained.fit(X_train, y_train)
pred_lgbm_fix = pipe_lgbm_constrained.predict_proba(X_test)[:, 1]
auc_lgbm_fix = roc_auc_score(y_test, pred_lgbm_fix)
print(f'[Pipeline LGBM Constrained + PCA] ROC-AUC: {auc_lgbm_fix:.4f}')

[Pipeline LGBM Constrained + PCA] ROC-AUC: 0.6867


In [34]:
# Пробуем еще воутинг:
clf1 = LogisticRegression(C=1, solver='liblinear', random_state=42)
clf2 = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42)
clf3 = SVC(probability=True, kernel='rbf', C=1, random_state=42)

eclf = VotingClassifier(
    estimators=[('lr', clf1), ('rf', clf2), ('svm', clf3)],
    voting='soft'
)

pipe_voting = Pipeline([
    ('scaler', StandardScaler()),
    ('voting', eclf)
])

pipe_voting.fit(X_train, y_train)
pred_vote = pipe_voting.predict_proba(X_test)[:, 1]
auc_vote = roc_auc_score(y_test, pred_vote)
print(f'[Pipeline Voting Ensemble] ROC-AUC: {auc_vote:.4f}')


[Pipeline Voting Ensemble] ROC-AUC: 0.7115
